### ISSUE TITLE
Widget Barre de recherche des extensions au DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#10]
08/04/2024 : premiers retours possibles (https://66142108335337008b2d7ab1--geoportal-extensions-samples.netlify.app/)

![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/df540687-8738-463a-a9d1-327873a07438)

04/06/2024 : 
Trois éléments en reste à faire : 

18/06/2024:
Plus que le dernier à cocher en validant https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/243

- [x] #225
- [x] #226
- [x] #234
- [ ] #242
- [ ] #257

**Comment by Kristell-5** [comment]
ok
