### ISSUE TITLE
Responsive et accessible

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#101]
L’interface cartographique devra être responsive et accessible aussi bien depuis un ordinateur que depuis un Smartphone. En effet, l’étude qualitative de 2023 menée auprès d’utilisateurs du Géoportail, a fait ressortir la double utilisation des utilisateurs du Géoportail que ce soit depuis un PC ou bien depuis l’application. A l’usage, les utilisateurs ont tendance à préparer en amont leur sortie sur la version web et à consulter l’application une fois en extérieur.

**Comment by elias75015** [comment]
https://github.com/IGNF/geopf-extensions-openlayers/issues/217
