### ISSUE TITLE
Procédure d’ajout et de recherches des fonds

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#109]
Procédure d’ajout et de recherches des fonds : Possibilité d’ajouter les fonds de cartes et gestion dans un unique bandeau. Pour se faire, la recherche s’effectue via le widget d’ajout de fonds de carte et de données puis via le bouton Gérer mes fonds de carte et données ». Une fois que le bandeau de recherche est superposé au bandeau de gestion de couches, soit une recherche manuelle peut être effectuée directement depuis l’onglet, soit une recherche globale basée sur la barre de recherche.

**Comment by elias75015** [comment]
Maquette Catalogue dispo. Menu catalogue à rendre conforme pour la V1.

**Comment by elias75015** [comment]
Catalogue OK en dev. A faire valider / recetter puis déploiement via prochaine release entrée carto
