### ISSUE TITLE
Classification et recherche du fond de plan

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#111]
Chaque fond de plan pourrait, ainsi, être classifié et recherché à partir d’informations telles que son/ses producteurs, nom ou bien thématiques associées. Une description succincte, une vignette représentant le fond de plan ainsi qu’un accès à des informations complémentaires pourraient être obtenues avant l’ajout du fond sur l’interface en cliquant pour ouvrir une fenêtre pop-up complémentaire.

**Comment by elias75015** [comment]
Maquette Catalogue dispo. Menu catalogue à rendre conforme pour la V1.

**Comment by elias75015** [comment]
Catalogue OK en dev. A faire valider/recetter et pousser en prod via prochaine release entrée carto.
