### ISSUE TITLE
Recherche élargie

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#113]
Recherche élargie : Possibilité de rechercher de nombreux fonds de carte proposés dans le catalogue. Actuellement le nombre de fond est défini et limité.

**Comment by elias75015** [comment]
Maquette Catalogue dispo. Menu catalogue à rendre conforme pour la V1.

**Comment by elias75015** [comment]
Catalogue OK en dev. A faire valider et pousser en prod.
