### ISSUE TITLE
Outils

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#116]
Outils : Les outils doivent rester accessibles et facilement identifiables puisqu’ils sont souvent utilisés. La possibilité d’avoir un bandeau dédié et personnalisable via une recherche pourra permettre de mettre en avant les outils proposés par l’interface puis à terme par tous les producteurs.

**Comment by elias75015** [comment]
Ticket à préciser ou fermer
