### ISSUE TITLE
Widget Calcul de profil altimétrique des extensions au DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#15]

**Comment by elias75015** [comment]
Besoin Maquette


Ce qu'on a actuellement en mode DSFR :

![image](https://github.com/user-attachments/assets/6ae4409d-92cc-4f00-8cc8-2696dd660c4d)

![image](https://github.com/user-attachments/assets/9babcb34-3b31-497b-9fe9-21843f18d5e2)

**Comment by Kristell-5** [comment]
J'ai fait une première maquette draft, mais je rencontre un problème pour vraiment comprendre le composant, vu qu'il n'est pas disponible sur Figma. Peut-être qu'il faudrait directement travailler à 4 mains avec le dev qui traite le sujet.



![Image](https://github.com/user-attachments/assets/06b8ef4c-db3e-4592-a11a-ddade88f258c)



![Image](https://github.com/user-attachments/assets/e518b6e9-2476-466e-a0f4-6edc00519ab6)
https://github.com/GouvernementFR/dsfr-chart

**Comment by elias75015** [comment]
A voir si c'est faisable avec DSFR Charts...pas sur en fait. Sinon, faudrait bidouiller le rendu actuel pour que ce soit plus conforme au DSFR.

@azarz est assigné pour ce sujet, je lui réattribue pour que vous voyiez ensemble suivant vos dispos.

**Comment by azarz** [comment]
En tout cas, ce n'est pas possible d'utiliser DSFR Charts dans les extensions, car il faut utiliser Vue.js pour utiliser DSFR Charts. Par contre, ce ne doit pas être très compliqué d'adapter le widget actuel pour que le rendu soit similaire à DSFR Charts, d'autant que ce dernier est open source donc sa configuration est facilement accessible.

**Comment by azarz** [comment]
Dans la PR https://github.com/IGNF/geopf-extensions-openlayers/pull/163, j'adapte le profil actuel au DSFR : bonnes couleurs, bonne police.

Cela permettra à @Kristell-5 d'avoir une meilleure base pour les maquettes.

**Comment by elias75015** [comment]
@Kristell-5 est-ce que la proposition d'Amaury peut être intégrée à l'entrée cartographique comme premier jet en attendant la maquette ?

**Comment by Kristell-5** [comment]
Oui, complètement ! Petite remarque : est-il possible d'accentuer les couleurs pour la version sombre ?

**Comment by elias75015** [comment]
Sans trop m'avancer je dirais que oui. Cette version est pour te donner des billes en attendant ta proposition. Faudra nous dire quelle couleur par exemple.

**Comment by elias75015** [comment]
@IGNFhc à intégrer en l'état à l'entrée carto en attendant la maquette
