### ISSUE TITLE
Widget Calcul d'azimuth des extensions au DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#18]
08/04/2024 : premiers retours possibles (https://geoportal-extensions-samples.netlify.app/)

![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/201574b8-9299-47db-9c56-16ef65988591)

**Comment by elias75015** [comment]
Recette dans #274

**Comment by quentinpage** [comment]
les icones ne sont pas les mêmes.
il y a une mesure des distance, (qui est le même)
il y a une mesure d'azimut qui est le même
mais la distance de l'aire est différente 
et la 4e mesure ????
