### ISSUE TITLE
Refactorisation des extensions Geoplateforme pour OpenLayers au DSFR (PT-5)

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#2]
**PT-5**
Les extensions Géoplateforme doivent être proposées au DSFR pour limiter les surcouches DSFR au niveau du portail.

Le dépôt sur lequel les travaux sont réalisés : https://github.com/IGNF/geoportal-extensions-openlayers

Tâches générales : 
- [x] #7

Pour chaque widget, un ticket est créé pour suivre l'avancement : 

- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #22

**Comment by azarz** [comment]
@elias75015 tout est coché ! ✅
