### ISSUE TITLE
IO - comportement cartes en version responsive

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#213]
### Description

- [x] Bug
Sur https://ignf.github.io/cartes.gouv.fr-entree-carto/ avec EDGE, la carte ne se déplace en vue adaptative :
- version mobile (360x740 testé) 
- version tablette (712x1138 testé)

Cela fonctionne par contre après s'être localisé.
Fonctionne sous firefox

- [x] Evolution
Evolution à prévoir (et définir) : gérer header et footer (minimiser, faire disparaitre ou autre) en deça du point de rupture 1248 

### Comportement attendu

Déplacement carte possible.

**Comment by quentinpage** [comment]
maintenant l"emprise géographique pour un département ne prend pas tous le département.
