### ISSUE TITLE
Widget Drawing des extensions au DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#22]

**Comment by elias75015** [comment]
Besoin maquette + icone

**Comment by elias75015** [comment]
@Kristell-5 si je ne me trompe pas toujours en attente de proposition de maquette sur les icones du drawing. Sinon je veux bien que tu me dises où c'est si j'ai raté quelque chose. Merci ! 

Je reporte au sprint S8 (fin octobre)

**Comment by Kristell-5** [comment]
J'ai initié un document pour la dircom qui se trouve ici. J'essaie de vous informer dès qu'ils sont créés. N'hésitez pas à faire des commentaires s'il y a des manques dans les pictos. https://www.figma.com/design/PGPNlVVsqRUi1adA4v6fCH/Picto-entr%C3%A9e-carto?node-id=0-1&t=fdxBmEt6zsT74kCh-1

**Comment by elias75015** [comment]
Icones ici, à implémenter sur les extensions en mode dsfr (voir ticket https://github.com/IGNF/geopf-extensions-openlayers/issues/37): https://www.figma.com/design/HzI4HxsNl6U63XQ39XP8rj/Ic%C3%B4nes-DSFR%40IGN?node-id=18-5299&node-type=canvas&t=jlQ7jopkUAuw2GHq-0
