### ISSUE TITLE
Plein écran

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#221]
Un bouton permettant d'afficher la carte en fullscreen / plein écran doit être présent en bas à droite de l'entrée cartographique.

On utilisera l'icon associé de l'espace collaboratif de manière homogène par rapport aux autres outils.

![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/ae983636-d821-450d-b054-bc5b9560c853)

Voir la boite à outil :

https://www.figma.com/design/s7gqdbxLRzPinQCRcoYXcT/Mise-en-DSFR-des-Widgets?m=dev

**Comment by Kristell-5** [comment]
ok
