### ISSUE TITLE
réaliser une version responsive du layerSwitcher pour affichage en mode mobile

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#222]
Pour la V0 : 
- [x] #224

Pour la V1 : 
- [x] #223

**Comment by elias75015** [comment]
Nécessité d'avoir une proposition de maquette pour le mode mobile

**Comment by Kristell-5** [comment]
Proposition faite sur #223

**Comment by elias75015** [comment]
A monter sur entrée carto.
