### ISSUE TITLE
réaliser une version responsive du LayerSwitcher pour le mode mobile

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#223]
Une maquette "mode mobile" du layerswitcher est souhaité avant de débuter tout travail sur ce sujet.

La première idée était de positionner le bouton et la fenêtre du layerswitcher en bas de la fenêtre carto, qui s'ouvre sous la carte.

**Comment by Kristell-5** [comment]
Ci-joint un screenshot des maquettes qui se trouvent dans la section dédiée aux devs sur Figma. Sur mobile, ayant moins de place, je propose cette solution. À voir si c'est possible.

![Image](https://github.com/user-attachments/assets/8dc1b4ff-f00f-4268-b874-c8570366431f)

**Comment by elias75015** [comment]
OK si j'ai bien suivi ca a été fait côté extensions, mais pas encore intégré sur l'entrée carto. 
On essaye de tester ça pour la semaine prochaine (S7)

**Comment by elias75015** [comment]
Côté entrée carto, en mode mobile, le layerswitcher est difficilement utilisable, une fois ouvert les boutons de droite disparaissent/sont cachés et aucun moyen de le fermer.

J'imagine qu'il faudrait que le panel de gestion des couches du layerswitcher passe au dessus de tout le reste ?
