### ISSUE TITLE
absence de liste dans le champ type pour une recherche avancée

### ISSUE THREAD

**Issue by quentinpage** [IGNF/cartes.gouv.fr-entree-carto#230]
### Description

sur une tablette android lors d'une recherche avancé, quand l'utilisateur choisi "lieux/toponymes", il doit avoir une liste "rempli" de "type"!
mais sur la tablette, la liste est vide.

**Comment by elias75015** [comment]
Le problème ne se pose que sur tablette et pas sur téléphone ?

As-tu moyen de faire un screenshot du problème ?

**Comment by quentinpage** [comment]
le problème est sur smartphone (téléphone en français), la difficultés proviens du fait qu'il n'y a pas de choix dans le champs  "type" 
je te mets en copie la capture d'écran mais cela n'a pas vraiement de sens. quand l'utilisateur clis sur le tria,ngle de droite du champs type il est apparait vide

![Image](https://github.com/user-attachments/assets/7f843fef-63ef-4afb-b55c-1d8564592bd5)

**Comment by elias75015** [comment]
Sur mobile multifonctions les propositions apparaissent ici : 

![Image](https://github.com/user-attachments/assets/917515d6-4c5c-4cde-9fe9-7b8d20078011)


Mais je vais modifier l'élément pour en faire une liste déroulante, car sur firefox ca ne fonctionne pas bien.

**Comment by IGNF-Xavier** [comment]
Ok
