### ISSUE TITLE
LayerSwitcher en mode sombre

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#232]
le titre des couches est invisible en mode sombre et celui-ci ne s'applique pas au Layerswitcher

![Capture d’écran du 2024-06-07 15-36-32](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/dd6019b1-3fdb-4c62-820d-5674632864c7)

**Comment by elias75015** [comment]
Quasi OK. Reste à passer les différents icones du LS dans la couleur adéquate lorsqu'on le met en mode sombre, car actuellement illisible 👍 


![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/b739b428-fcff-4b66-9e07-2b1449de13fa)

**Comment by azarz** [comment]
Pour les icones, c'est comme pour le search. Il va falloir faire une refonte totale de la manière d'afficher des icônes, en passant par un mask plutôt que par une background-image. En effet, le passage de mode sombre à mode clair est géré pour les couleurs par des variables css. Le mask peut accéder à ces variables, mais pas une background-image.

Le fix que j'ai fait sur le search (icônes différentes pour mode sombre et clair) ne marche que pour le mode par défaut des utilisateurs, mais pas lorsqu'on change d'un mode à l'autre via le site. C'est déjà ça...

**Comment by azarz** [comment]
Refonte ici : https://github.com/IGNF/geoportal-extensions-openlayers/pull/91
