### ISSUE TITLE
Changement de design pour l'accès à la recherche avancée

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#234]
Actuellement, la recherche avancée passe par un icone rouage : 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/d0cc4059-7c60-4ab8-97ca-35d562132e85)

Il faudrait à la place mettre un lien "Recherche avancée" en dessous, quand l'option est activée, tel que décrit sur le figma : 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/7d73c1c4-2f73-49f4-aa07-7a9e52119722)

https://www.figma.com/design/s7gqdbxLRzPinQCRcoYXcT/Mise-en-DSFR-des-Widgets?node-id=286-4495&m=dev

La deuxième solution (radios + lien sur la même ligne) est à privilégier a priori, en attente de confirmation.

**Comment by Kristell-5** [comment]
ok
