### ISSUE TITLE
Recette : #48 Carte Centrale

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#237]
Ticket de recette du ticket #48 (et ses sous-tickets #103 #104 #105 #106).

Mettre les commentaires et remarques liés à la recette #48 (et ses sous-tickets #103 #104 #105 #106) dans ce ticket.

**Comment by quentinpage** [comment]
ok

**Comment by elias75015** [comment]
@Kristell-5 rien à ajouter ? 

Le premier commentaire de Quentin concerne la version mobile du site qui est à venir : on fera un ticket de recette dédié à ce moment.

**Comment by Kristell-5** [comment]
c'est ok pour moi
