### ISSUE TITLE
Recette : #25 Navigation sur la carte

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#238]
Ticket de recette du ticket #25 (et ses sous-tickets #66 #67 #68 #69).

Mettre les commentaires et remarques liés à la recette du #25 (et ses sous-tickets #66 #67 #68 #69) dans ce ticket.

**Comment by elias75015** [comment]
> la mini-carte est replié par défaut dans tous les navigateurs sauf pour firefox
> les outils de contrôle de d'échelles sont en bas à droite pour tous les navigateurs sauf Firefox où ils sont à gauches

Je ne constate pas : 

La Minivue est repliée que ce soit sous FF ou Chrome
L'echelle est située que ce soit sous FF ou Chrome

Firefox :
![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/a82f9557-c048-471b-9091-c02b631555c2)

Chrome :
![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/2da54572-fb97-42bf-aa12-f0b7b8237595)


Peux-tu me confirmer que tu continues de reproduire ?

**Comment by quentinpage** [comment]
j'avais constaté la mini-carte était replié seulement pour firefox. c'était iun comportement différent (pas un bug).
maintenant le comportement est identique sur Firefox, edge, chrome et android!
