### ISSUE TITLE
AU clic sur oeil de couches, plus de carte et impossible de la remettre

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#249]
### Description

![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/98382923/39d9f28c-1931-4926-98ba-288d37b4802e)

J'ai cliqué sur l'oeil, ça disparait, je reclique dessus, il ne se passe rien.

Constaté sur https://cartes.gouv.fr/cartes/

### Comportement attendu

Que cela fonctionne

### Comment reproduire l'anomalie

Cliquer sur l'oeil
Recliquer sur l'oeil

**Comment by elias75015** [comment]
Je ne réussis pas à reproduire.

Peux tu me fournir l'environnement utilisé :
- navigateur et sa version 
- OS et sa version

**Comment by quentinpage** [comment]
test avec android OK
test avec edhe pk
test chrome ok
test forefox NOK dans le premier temps (qui fait disparaitre l'affichage) l'oeil n'apparait pas caché (barré)!

par ailleurs je ne peux ### **_TOUJOURS PAS_** ni réassigné un ticket, ni crée de ticket ,i cha,nger de status pour le mettre en validé !!!!
la recette dans ces condition est TRES DIFFICILE (au mieu)!!!!!

**Comment by IGNF-Xavier** [comment]
Merci @elias75015 pour la réponse.
Je vais essayer sur mon ordi perso.
Je suis sur Firefox ESR déployé sur notre parc informatique. C'est peut-être de là que le pb vient.

@quentinpage le dépôt github se concentre sur les développements, la programmation de ceux ci et la gestion des bugs. Pour tout autre sujet, nous avons d'autres canaux

**Comment by IGNF-Xavier** [comment]
Le problème vient de firefox depuis l'IGN.
Depuis ordinateur perso sur cartes.gouv.fr, à partir de la version 126.0.1, cela fonctionne.

**Comment by quentinpage** [comment]
ok pour firefox avec la version 128 esr

**Comment by elias75015** [comment]
OK je pense qu'on peut fermer, firefox ESR 115 date de plus d'un an, et le problème est certainement lié à cela. Il n'y aura plus de maintenance sur cette version d'ici septembre.



![Image](https://github.com/user-attachments/assets/7e680bc3-c827-4270-aa83-834cd1df2ed4)
