### ISSUE TITLE
Recette : #29 Minivue

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#250]
Recette du #29 pour le widget de minivue et de ses sous-tickets #78 et #79

**Comment by quentinpage** [comment]
recette pour edge 
ok mini vue pour déplie, la zone et la présence

recette pour chrome
ok mini vue pour déplie, la zone et la présence

recette pour Firefox
ok mini vue pour déplie, la zone et la présence

recette pour android
partiel mini vue pour déplie, la zone, la présence, l'orientation mais le niveau zoom de la carte me semble mal choisie
![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/125582900/0d502995-d057-43bd-86c9-bc38ed597b38)

**Comment by elias75015** [comment]
Le nouveau comportement est que la minivue ne s'affiche plus sur petit écran.

@quentinpage peux-tu restester stp ?

**Comment by quentinpage** [comment]
la mini carte est disponible sur ABDROID au format paysage et maintenant elle est centrée)
oui au format portrait elle n'est plusvisible
