### ISSUE TITLE
Recette : #31 LayerSwitcher - version simple

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#251]
Recette du #31 concernant le layerSwitcher dans sa version simple du MVP de juin 2024 : 
- #8 
- #83
- #89
- #90
- #91
- #92
- #93
- #96
- #97

Les autres fonctionnalités listées dans le #31 sont à prioriser pour les prochains sprints et ne sont pas à recetter dans ce ticket

**Comment by quentinpage** [comment]
recette pour edge 
ok mini vue pour déplie, la zone et la présence
nok gestion de plusieurs couche (1 seul est possible ==plan ign v2)
nok ajout de coucjes supplémentaires
ok apparition/masques couche
ok opacité
? position des couches


recette pour chrome
ok mini vue pour déplie, la zone et la présence
nok gestion de plusieurs couche (1 seul est possible ==plan ign v2)
nok ajout de couches supplémentaires
ok apparition/masques couche
ok opacité
? position des couches

recette pour Firefox
ok mini vue pour déplie, la zone et la présence
nok gestion de plusieurs couche (1 seul est possible ==plan ign v2)
nok ajout de couches supplémentaires
nok apparition/masques couche
ok opacité
? position des couches

recette pour android
partiel mini vue pour déplie, la zone, la présence, l'orientation mais le niveau zoom de la carte me semble mal choisie
![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/125582900/0d502995-d057-43bd-86c9-bc38ed597b38)
ok mini vue pour déplie, la zone et la présence
nok gestion de plusieurs couche (1 seul est possible ==plan ign v2)
nok ajout de couches supplémentaires
ok apparition/masques couche
ok opacité
? position des couches

**Comment by elias75015** [comment]
@quentinpage pour l'instant, le seul moyen d'ajouter des couches à l'interface est de passer par la barre de recherche, en cliquant sur "cartes et données", et en tapant le nom de couches que tu veux ajouter (et cliquer sur les suggestions qui apparaissent).

Peux-tu stp retester le gestionnaire de couches en ajoutant quelques couches avec la barre de recherche ? Tu pourras ainsi retester tout ce que tu as mis en "nok" ou en "?"

**Comment by quentinpage** [comment]
je vois bien les suggestion des couches par la méthode "cartes et données", et en tapant le nom de couches .

mais la couche ne s'affiche pas et en se faisant disparaitre le gestionnaire puis en le faisant réapparaitre la couche "plan IGN V2" se démultiplie
la disparition du gestionnaire de couche se fait avec l'option "gestionnaire de couches" complément à droite. 
la couches "ortho-express 2024(WMTS)" a déja été double cliuqué avant la capture d'écran.
le contenu du gestionbnaires de couche est le résultat réalisé sous chrome

mais ces résultats sont identiques sur firefox et edge. mais ce comportements n'apparaissent pas pour d'autres coiuches.
la couche  "ortho-express 2024(WMTS) est peut être fausse.

![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/125582900/2484ec4b-a74f-4834-8688-864e57c9bc15)

dans tous les cax la couche "plan IGN v2" se multipli

ps:
le bouton cartes et données apparait sur android mais ne donne pas de proposition géographique

**Comment by elias75015** [comment]
Bonjour @quentinpage,

peux-tu retester ?

Nous avons ajouter un test d'unicité sur le layerSwitcher pour ne pas avoir plusieurs fois la même couche dedans pour un service donné (tu pourras donc avoir PLAN IGN (WMS) et PLAN IGN (WMTS) dans le gestionnaire de couche).

De mon côté, la couche ortho-express-2024 s'affiche bien : 


![Image](https://github.com/user-attachments/assets/d79e870e-ff13-425a-a1ab-a903f0bf9fcc)

Il faut se placer vers Bergerac, sinon l'absence de données renvoie du blanc

**Comment by quentinpage** [comment]
ok pour le comportement de gestion des couches.

la même couche ne se multiplie plus même avec firefox.
