### ISSUE TITLE
Recette : #108 Barre de recherche version desktop

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#254]
Recette du #108 sur la barre de recherche en version "Bureau" et des tickets associés : 
- #10
- #114
- #226
- #234

A noter : les tickets #225 et #242 liés au composant en mode mobile ne sont pas à prendre en compte dans cette première recette du composant

**Comment by quentinpage** [comment]
firefox 
nok recherche avancée avec coordonnées, iil ne rend que des valeurs entier des "." ou "," ne sont pas reconnu par coord
ok pour la recherche avancée pour "lieux/toponymes" choix pas de liste proposée
nok recherche avancée par adresse, il n'y a que le nom de la ville même pas de nom de rue
ok recherche simple
ok pour la complexion
ok pour l barre de recherche unique 
ok disign recherche avancée
![Image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/125582900/769a6603-dcbd-4ef7-8aab-ddb6ead0a8cd)

android
nok recherche avancée avec coordonnées, iil ne rend que des valeurs entier des "." ou "," ne sont pas reconnu par coord
nok pour la recherche avancée pour le 2e choix pas de liste proposée
nok recherche avancée, il n'y a que le nom de la ville même pas de nom de rue
ok recherche simple
ok pour la complexion
ok pour la barre de recherche unique 
ok design recherche avancée

chrome
nok recherche avancée avec coordonnées, iil ne rend que des valeurs entier des "." ou "," ne sont pas reconnu par coord
ok pour la recherche avancée pour "leux/toponymes" choix pas de liste proposée
nok recherche avancée par adresse, il n'y a que le nom de la ville même pas de nom de rue
ok recherche simple
ok pour la complexion
ok pour la barre de recherche unique 
ok design recherche avancée

edge
nok recherche avancée avec coordonnées, iil ne rend que des valeurs entier des "." ou "," ne sont pas reconnu par coord
ok pour la recherche avancée pour "lieux/toponymes" choix pas de liste proposée
nok recherche avancée par adresse, il n'y a que le nom de la ville même pas de nom de rue
ok recherche simple
ok pour la complexion
ok pour l barre de recherche unique 
ok disign recherche avancée

ps: l'emprise pour une recherche par département est ok avec edge

**Comment by elias75015** [comment]
>  nok recherche avancée avec coordonnées, iil ne rend que des valeurs entier des "." ou "," ne sont pas reconnu par coord

Effectivement ! On corrige au plus vite sur les API JavaScript et je te préviens quand tu peux retester.

>  nok recherche avancée par adresse, il n'y a que le nom de la ville même pas de nom de rue

Bien vu, il y a aussi un problème. On corrige dès que possible.

A corriger : 
- [ ] Recherche avancée par coordonnées ne prend que des entiers
- [ ] Recherche avancée par adresse : le formulaire ne contient pas tous les champs

**Comment by elias75015** [comment]
@quentinpage le premier point soulevé est normalement corrigé : 


>     nok recherche avancée avec coordonnées, iil ne rend que des valeurs entier des "." ou "," ne sont pas reconnu par coord

**Comment by elias75015** [comment]
@quentinpage le second point aussi

> nok recherche avancée par adresse, il n'y a que le nom de la ville même pas de nom de rue

Le fonctionnement désormais gris le bouton "loupe" lorsque la recherche avancée est ouverte. Le nom de la rue utilisé dans la recherche avancée par adresse est celui de la barre de recherche principale.

Par exemple : 


1 - je tape "italie" dans la barre de recherche



![Image](https://github.com/user-attachments/assets/3ee0ee0f-cc7c-487d-96a4-76939559d58c)



2 - j'ouvre la recherche avancée : le bouton est grisé



![Image](https://github.com/user-attachments/assets/c2314266-6b76-44e4-9b2f-03816f6ae59a)



3 - je tape "Toulouse" dans nom de ville et clique sur "Chercher"



![Image](https://github.com/user-attachments/assets/623a006c-5e3e-438e-85c3-800867a6533f)

**Comment by quentinpage** [comment]
ok pour le fonctionnement adresse "simple" puis avancés sur Firefox
ok pour le fonctionnement adresse "simple" puis avancés sur chrome
ok pour le fonctionnement adresse "simple" puis avancés sur android (smartphone)
nok pour le fonctionnement de edge. quand un utilisateur commence par écrire le nom d'une rue dans la recherche simple puis demande une recherche avancé et commence à tapper la complexion automatique lui propose des valeurs mais lors de la validation de ce choix, le champ 'code INSEE' est rempli avec le nom proposé


![Image](https://github.com/user-attachments/assets/69763f87-cebb-4335-8209-1931371dfffc)
ce qui donne


![Image](https://github.com/user-attachments/assets/5526e5d3-9f87-4382-8a4c-30f439944061)

évidemment il n'y a aucune réponse.mais en enlevant la valeur du champ "code INSEE", le site trouve des réponces
ce fonctionnement me semble pas très intuitif surtout en bloquand la recherche "simple au moment de la recherche avan


ok pour la recherche par coordonnées avec des "," ou des "." sur edge
ok pour la recherche par coordonnées avec des "," ou des "." sur firefox
ok pour la recherche par coordonnées avec des "," ou des "." sur chrome
nok sur android (smartphone), la recherche par coordonnées amène à rien.

**Comment by elias75015** [comment]
@quentinpage 
Pour l'autocomplétion sur Edge, c'est un mauvais comportement du navigateur.
Essaye de supprimer ton historique d'informations personnelles sur Edge pour voir si le problème persiste.

La recherche par coordonnées sur Android fonctionne chez moi. Le problème est qu'elle n'est pas très visible car seul un recentrage de la carte est effectué. Il faudrait ajouter un marker à la carte pour matérialiser le point ciblé. Je vais créer un ticket d'évolution pour ça.

Selon moi, ces deux remontées que je vais noter dans des tickets si elles sont confirmées, ne sont pas bloquantes pour valider la barre de recherche "simple" en Desktop.

@Kristell-5 à toi de décider.

**Comment by quentinpage** [comment]
oui en supprimant l'historique, le site ne propose plus rien mais le fait de le réaliser à la main cette suppression (ou la non validation du choix proposé)  est une simple remarque non loquant.

je suis d'accord ce n'est pas bloquant simplement gênant.

les recherches par coordonnées décimal fonctionnent sur tous les navigateurs testés

**Comment by elias75015** [comment]
Ticket d'évolution pour ajouter un marker lorsqu'on recentre la carte avec la barre de recherche : https://github.com/IGNF/geopf-extensions-openlayers/issues/147

**Comment by quentinpage** [comment]
pour edge, il a toujours une recherche vide si le nom de la ville dans la recherche avancée est différente de celai de la recherche simple et la recherche simple est inaccessible si la recherche avancée est ouverte,, sinon toutes les remarques sont levées. ce point n'est pas bloquant selon moi

pour firefox, il a toujours une recherche vide si le nom de la ville dans la recherche avancée est différente de celai de la recherche simple et la recherche simple est inaccessible si la recherche avancée est ouverte, sinon toutes les remarques sont levées. ce point n'est pas bloquant selon moi

pour chrome, il a toujours une recherche vide si le nom de la ville dans la recherche avancée est différente de celai de la recherche simple et la recherche simple est inaccessible si la recherche avancée est ouverte,, sinon toutes les remarques sont levées. ce point n'est pas bloquant selon moi

**Comment by elias75015** [comment]
OK merci : à voir à terme comment rendre plus intuitive la recherche avancée.

On valide cette première version desktop simple de la recherche.
