### ISSUE TITLE
Réduction taille du panel barre de recherche(Expérimentation suite aux premiers retours utilisateurs)

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#257]
Les premiers retours utilisateurs font état d'une barre de recherche qui prend trop d'espace, aussi bien en mode desktop qu'en mode mobile.

L'idée serait de réduire l'espace pris par le panel en fonction du focus.

1 - le focus n'est pas sur l'input : 
Desktop : 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/c4e778dc-5a4f-49b9-996e-2692ecfe682e)

Mobile :
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/868c5811-061d-40be-9783-feee4129ecde)

2 - le focus est sur l'input :
Desktop : 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/2d856408-cc57-47c7-8cfd-17f5530063c2)

Mobile :
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/edad2714-8ac0-4e95-a2a1-5e516cd5bd83)

3 - des suggestions d'autocomplétion apparaissent et le focus est sur l'input ou sur les résultats proposés : 
Desktop : 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/9a6fffc7-24bb-42b2-b2d9-964efdbc1f32)

Mobile :
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/2b13e1af-f393-4f1c-9edf-41daf41a0564)

**Comment by elias75015** [comment]
@Kristell-5 ca correspond à ce que tu voudrais tester ? j'ai fait des screenshots à l'arrache, mais l'idée est juste d'afficher ou non des élements et de déplacer les boutons en mode mobile pour qu'ils soient sur la même ligne que la barre de recherche.

D'ailleurs il me semble que le DSFR impose une longueur minimale pour la barre de recherche non ? C'est compatible avec la proposition ?

**Comment by Kristell-5** [comment]
Oui c'est exactement ça.

**Comment by elias75015** [comment]
Autre question : est-ce que tu veux une transition pour l'ouverture / fermeture du panneau avancé ?

**Comment by Kristell-5** [comment]
Oui, si possible avec un dépliement (1 seconde pour la sortie et 2 secondes pour la rentrée). Concernant la barre de recherche, elle doit permettre un minimum de 27 caractères, donc je vais refaire une proposition pour la version mobile.

**Comment by elias75015** [comment]
Fonctionnement décrit dans maquette figma pour réduire l'espace pris par la barre de recherche : doit se déplier au focus des éléments du widget, se replier à la perte de focus des éléments html du widget.

**Comment by azarz** [comment]
Traité dans les extensions :
https://github.com/IGNF/geoportal-extensions-openlayers/pull/125

**Comment by elias75015** [comment]
Toujours pas bon :

- Retirer le padding de 15px à droite et à gauche
- Mettre 490 px de large
- Enlever la marge après le dernier icon

**Comment by elias75015** [comment]
#303
