### ISSUE TITLE
clef partagée pour la gestion du consentement (@codegouvfr/react-dsfr finalityConsent eulerianAnalytics)

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#266]
Avoir une clé partagée entre les différentes briques de cartes.gouv pour la conservation de certains paramètres communs dans la navigation : 
- collecte ou non de cookies
- theme d'affichage (dark/light)

**Comment by lowzonenose** [comment]
Actuellement, on a prit le partie d'utiliser la clef de **cartes.gouv.fr**.
Le nom n'est pas ouf, mais ça fera le job en attendant...

**Comment by elias75015** [comment]
C'est OK sur la main en fait.
