### ISSUE TITLE
Recette : #33 #34 #35 Outils de mesure

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#274]
Recette des outils de mesure (distance, aire, azimuth) : 

- #16
- #17
- #18
- #33
- #34
- #35

**Comment by quentinpage** [comment]
nok pour firefox
pour les outils de mesure sur firefox, il y a une liste de 3 outils sur la carte (mesure d'une distance, mesure d'une surface et mesure d'une azimut) mais l'image ne correspond pas à celle du ticket. de plus les outils peuvent être sélectionnés (surbrillance) mais ils semblent ne pas fonctionner et ils ne peuvent plus être désélectionnés.

![Image](https://github.com/user-attachments/assets/20e13c73-c0a9-482c-a18a-c3568fc4cad7)

ok pour chrome
pour les outils sur chrome il y a une liste de 3 outils sur la carte (mesure d'une distance, mesure d'une surface et mesure d'une azimut). les outils fonctionne et ils sont dé-sélectionnables. les objets créés disparaissent alors
cependant l'image ne correspond pas à celle du ticket

ok pour edge
pour edge,il y a une liste de 3 outils sur la carte (mesure d'une distance, mesure d'une surface et mesure d'une azimut). les outils fonctionne et ils sont dé-sélectionnables. les objets créés disparaissent alors
cependant l'image ne correspond pas à celle du ticket

**Comment by quentinpage** [comment]
mesure de l'aire avec des unité qui se chousi automatiquement ok sur edge et chrome

**Comment by quentinpage** [comment]
ok pour android (smartphone)
pour android ,il y a une liste de 3 outils sur la carte (mesure d'une distance, mesure d'une surface et mesure d'une azimut). les outils fonctionnent et ils sont dé-sélectionnables. les objets créés disparaissent alors
cependant l'image ne correspond pas à celle du ticket

**Comment by elias75015** [comment]
Pour les icones des bouttons et l'aspect, le ticket n'est pas à jour par rapport au rendu, j'aurais dû prévenir.

On va laisser @Kristell-5 valider l'aspect.

Des problèmes ont été réglés sur le github.io : désormais sélectionner un outil de mesure déselectionne automatiquement n'importe quel autre outil de mesure en cours d'utilisation.

**Comment by quentinpage** [comment]
il y a toujours des difficultés à utiliser sur firefox, les outils de mesures

**Comment by elias75015** [comment]
Quelles sont les difficultés qui persistent ?

**Comment by IGNF-Xavier** [comment]
@elias75015 
C'est encore la version ESR de Firefox qui n'est pas supportée. cf. #249 
Les outils sont sélectionnés, ne remplissent pas leur fonction et demeurent sélectionnés.


![Image](https://github.com/user-attachments/assets/55399919-4b6b-4e87-a569-0bdea15ea085)

**Comment by IGNF-Xavier** [comment]
@Kristell-5 eux-tu valider l'aspect des boutons et clore le ticket.
Le ticket #287 prend le relai pour la compatibilité Firefox ESR.

Merci
