### ISSUE TITLE
Recette : #77 Légendes - version simple

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#276]
Recette du composant "Légendes" dans une version simple, avec un accès via un bouton dédié uniquement : 
- #77

**Comment by quentinpage** [comment]
partiel sur chrome. la légende sur le plan IGN V2 apparait mais pas les données et les autres couches. les couches sont proposées dans une liste mais elles n'apparaissent pas dans le gestionnaire de couche et donc leurs légendes n’apparaissent pas non plus.

![Image](https://github.com/user-attachments/assets/148618a0-4031-47d0-ba83-4d6ac74e920e)


partiel sur android (smartphone). la légende sur le plan IGN V2 apparait mais pas les données et les autres couches. les couches ne sont même pas proposées dans une liste. quand l'utilisateur demande "cartes et données" et qu'il précise "topo" par exemple, le site ne propose que des adresses (la couche ocsge a aussi était essayée) l'option du choix des données ne fonctionnent pas . 

 partiel pour firefox la légende sur le plan IGN V2 apparait il est également possible faire apparaitres les légendes des autres couches mais le replis des légendes fait uniquement dans le menu paramètre en décochant légende mais pas en recliquant sur le menu légende ou sa croix.

partiel sur edge. la légende sur le plan IGN V2 apparait mais pas les données et les autres couches. les couches sont proposées dans une liste mais elles n'apparaissent pas dans le gestionnaire de couche et donc leurs légendes n’apparaissent pas non plus.

**Comment by quentinpage** [comment]
oui je sais.j'ai seulement remarqué l'absence pour certaines couches de la légende.
les couches apparaisse dans la lsite des couches supposés disponible mais il n'y a pas de couches donbc pas de légende

**Comment by elias75015** [comment]
OK merci. Si c'est juste l'absence de légende qui est noté, c'est lié ç la donnée manquante derrière et pas au widget.

Dans une version avancée du widget, on proposera certainement un moyen de mieux gérer l'absence de légende. 

@Kristell-5 quelque chose à remonter ?
