### ISSUE TITLE
Ajouter les trackers ciblés sur les éléments souhaités avec data-fr-analytics-click

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#279]

**Comment by lowzonenose** [comment]
Test réalisé sur le projet dsfr sur l'api analytics : ça ne fonctionne pas sur les exemples SPA vue, react ou angular !?

Je fais donc une issue sur le projet dsfr afin d'avoir des éclaircissements sur les frameworks.

**Comment by elias75015** [comment]
@Kristell pourras-tu nous fournir la description des KPI dans leur dernière version s'il y en a une ?

**Comment by Kristell-5** [comment]
https://ignf.sharepoint.com/:x:/r/sites/EXT-UXUIInterfacesGPF/Documents%20partages/Animation%20MVP/Les%20diff%C3%A9rents%20indicateurs%20de%20performance%20(KPIs).xlsx?d=wf6cda35bbef64d05b6096d560c2ac8b5&csf=1&web=1&e=lpgn6X

C'est un fichier partagé avec d'autres équipes de Cartes.Gouv, il peut évoluer.
