### ISSUE TITLE
Echelles FC-6

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#28]
FC-6

- Échelles : 1/xxxxx et échelle graphique. Les deux échelles permettent une meilleure compréhension par les utilisateurs qui pourraient être plus sensibles à l’une ou l’autre des représentations.

**Questions** 

*L'échelle est-elle éditable par l’utilisateur ?* 
Non en dessous du point de rupture petit écran, oui sinon.

**Comment by Kristell-5** [comment]
ok
