### ISSUE TITLE
Support de Firefox ESR non assuré

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#287]
### Description

De manière générale, le comportement des boutons sur Firefox ESR n'est pas assuré.

- [ ] Sur la capture ci-dessous, les outils de mesure ne fonctionnent pas et reste sélectionné lorsqu'on en sélectionne un autre : 
![image](https://github.com/user-attachments/assets/64dcd6bc-ac07-4feb-ad05-bc7e72c3e2b6)
- [ ] Ici les boutons "fermer ne fonctionne pas (l'alignement n'est pas bon non plus
![image](https://github.com/user-attachments/assets/8c359311-362f-4b94-b521-69c83aea0ee3)
- [ ] [#249](https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/249) Problème de l'oeil d'affichage des couches
- [ ] Le menu de recherche avancée n'apparait pas
![image](https://github.com/user-attachments/assets/7bac0c15-378a-42f2-86a5-acd1cbf95c6f)

### Comportement attendu

Compatibilité avec Firefox ESR

### Comment reproduire l'anomalie

Se rendre sur https://cartes.mut-dev.ign.fr/cartes/

**Comment by IGNF-Xavier** [comment]
Avant de se pencher sur ce sujet, j'ai pris l'action de me renseigner sur le parc informatique ministerial

De plus, une nouvelle version ESR majeure est prévue dans 2 mois.

**Comment by elias75015** [comment]
Pour le dernier problème : 

> Le menu de recherche avancée n'apparait pas

Le nouveau comportement est que la recherche avancée n'apparait qu'au survol de la souris et au clic sur la barre de recherche.
Ce comportement ne fonctionne pas non plus avec FF ESR ?

**Comment by IGNF-Xavier** [comment]
Oui je confirme.

**Comment by elias75015** [comment]
Lié à ESR 115 a priori.
