### ISSUE TITLE
En version mobile : reporter le menu dans le burger

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#288]
### Le besoin que vous rencontrez

En version mobile, le burger ne contient que les liens du header et pas ceux du menu 
![image](https://github.com/user-attachments/assets/3300cae8-8886-4dfc-ad5e-c020a66adbe0)

### La solution que vous aimeriez

Disposer des menus du header

**Comment by elias75015** [comment]
Correctif livré sur la page démo (main). Sera intégré à la prochaine release.
