### ISSUE TITLE
Légende - ajuster la taille

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#290]
### Le besoin que vous rencontrez

L'espace laissé pour visionner la légende est très petit.
![image](https://github.com/user-attachments/assets/f538d634-329a-4b64-8fea-d2ce2249d7a3)

### La solution que vous aimeriez

Avoir une plus grande taille

### Les alternatives que vous avez considéré

Soit autoriser le redimensionnement
Soit avoir un redimensionnement adaptatif

### Autres éléments de contexte

En version mobile, le redimensionnement adaptatif semble plus oportun

**Comment by IGNF-Xavier** [comment]
Centrage et marge : OK
Par contre l'ajustement de taille en hauteur de la modale, ce n'est pas le cas

**Comment by elias75015** [comment]
@azarz tu pourras augmenter un peu le max-height de la div contenant la légende d'une couche ?


![Image](https://github.com/user-attachments/assets/4e3dacf3-3815-41ab-bcb2-10ddc9d29dbd)
