### ISSUE TITLE
Recette : #115 #117 #120 Menu de gestion des outils, première version

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#295]
Recette des tickets #115 #117 #120 : 

Le menu de droite de gestins des widgets accessible par le bouton "rouage" permet de : 
- ajouter des outils à l'interface cartographique
- retirer des outils de l'interfaces cartographique
- rendre visible / invisible des boutons de l'interface cartographique
- rechercher des outils via une barre de recherche à partir du nom ou de la description de l'outil

**Comment by elias75015** [comment]
Retour Kristell @IGNFhc : inverser les onglets "Mes Outils" et "Ajouter des Outils".

Par défault, au chargement, l'utilisateur est sur l'onglet "Ajouter des Outils".

**Comment by quentinpage** [comment]
ok sur firefox
il est sur Mes outils

ok sur chrome
il est sur Mes outils

ok sur edge
il est sur Mes outils

ok sur android (smartphone) mais peu lisible trop petit
il est sur Mes outils

**Comment by elias75015** [comment]
OK merci.

Sur smartphone, on passera par un autre cycle de développement quand on aura une maquette pour l'implémenter.
