### ISSUE TITLE
Recette : #36 #14 Widget de calcul d'isochrone

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#297]
Recette du #36 et #14 : ajout du widget d'isochrone possible, formulaire de paramétrage au DSFR, calcul d'isochrone isodistance possible.

**Comment by quentinpage** [comment]
en vidant manuellement le cache, l'option de calcul de l'isochrome est  accessible
est ce qu'il serait possible de réaliser une suppression automatique pour cette page (url) uniquement de manire automatique?

**Comment by elias75015** [comment]
Je ne crois pas. 

Une solution, pour les recettes, serait de toujours passer par une fenêtre en navigation privée.
