### ISSUE TITLE
Recette : #37 #13 Widget de calcul d'itinéraire

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#298]
Recette du https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/37 et https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/13 : ajout du widget d'itinéraire possible, formulaire de paramétrage au DSFR, calcul d'itinéraire possible.

**Comment by quentinpage** [comment]
ok sur firefox
pour isochrome et isodistance

ok sur chrome
pour isochrome et isodistance

ok sur smartphone
pour isochrome et isodistance

ok sur edge
pour isodistance
nok pour isochrome, l'outil apparait en grisé


![Image](https://github.com/user-attachments/assets/9d4bae82-3c5c-42c2-ab64-7a3117f5aaef)

**Comment by elias75015** [comment]
Salut Quentin,

peux-tu essayer de vider ton cache  (ou ouvrir une fenetre de navigation privée) sur Edge et me dire si le calcul d'itinéraire est toujours grisé ?

**Comment by IGNF-Xavier** [comment]
Sur Edge : OK.
Il faudrait faire attention par conte aux espacements sur les cellules actives (entouré en rouge sur cette image) qui déborde sur le texte : 


![Image](https://github.com/user-attachments/assets/82fcbc17-1b65-4c5d-ac14-1f352be90395)

@Kristell-5 un avis? Si confirmé par tes soins : 
- ouvrir un nouveau ticket
- fermer celui-ci

Dans tous les cas, ce n'est pas bloquant pour une mise en production.

**Comment by Kristell-5** [comment]
![image](https://github.com/user-attachments/assets/05ca39cd-42e3-4327-a59c-8d751696205e)
Les widgets ne sont pas obligés d'être alignés lorsqu'ils sont ouverts sur le picto, nous pouvons utiliser l'ensemble de l'espace pour limiter le scroll. Le mode de déplacement doit d'abord être mis sur piéton (piéton - voiture, alors que pour le moment c'est voiture - piéton).

Ci joint la maquette.

**Comment by elias75015** [comment]
Corrections à réaliser côté extensions.

Ticket créé : 
https://github.com/IGNF/geopf-extensions-openlayers/issues/150
