### ISSUE TITLE
Recette : #27 #77 Panel d'accès aux légendes

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#300]
Recette des tickets #27 et #77 : Ajout d'un widget Légendes en version simple, conforme au DSFR, où on peut accéder aux légendes des couches ajoutées si elles sont disponibles.

(Voir dernières améliorations : https://github.com/IGNF/geopf-extensions-openlayers/pull/137 )

**Comment by quentinpage** [comment]
avec firefox
la légende apparait bien mais comme pour les outils de mesures, la fenêtre ne se referme pas sauf en faisant disparaitre le bouton légende.
le menu légende cache le menu "gestion des couches"
![image](https://github.com/user-attachments/assets/afe16a4d-7de4-48f3-9d93-98440fd4beeb)

avec chrome
ok aucun problème

avec edge
ok aucun problème

avec android (smartphone)
ok aucun problème

**Comment by IGNF-Xavier** [comment]
Le problème est sur Firefox 115ESR.
Sur 129.0.1 : pas de problème.

**Comment by quentinpage** [comment]
ok pour la version de firefox 128 esr

**Comment by elias75015** [comment]
OK
