### ISSUE TITLE
Définir les éléments par défaut à l'ouverture de cartes.gouv

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#311]
@Kristell-5 et @IGNF-Xavier, à l'ouverture de l'entrée cartographique, définir : 

- [ ]  les outils disponibles par défaut. Les challenger ensuite avec un panel utilisateur
- [ ]  le fonds de carte initial : Ortho / Ortho + réseau routier / Fonds de plan IGN et son style. Le challenger avec les utilisateurs

A fixer pour la bascule derrière URL cartes.gouv.fr

A rechallenger à partir du résultat des sondes

**Comment by elias75015** [comment]
Première action suite à point avec Kristelle et Sonia : LayerSwitcher et Barre de recherche retirés du menu widgets : ils sont présents par défaut (et non modifiables)
