### ISSUE TITLE
Synchronisation de l'ordre des couches avec le permalien

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/cartes.gouv.fr-entree-carto#313]
> Si je change l'ordre des couches avant de partager le permalien le dernier changement n'est pas prise en compte dans le permalien. Les autres interactions : suppression/ajout de couche et modification de la visibilité fonctionnent correctement.

On traitera l'ordre des couches dans le permalien quand on prendra en compte toutes les couches (croquis, couche de calculs, import, ...), car ceci facilitera l'algo de changement de position d'une couche.
L’événement du gestionnaire de couche `layerswitcher:change:position` est maintenant disponible.

_Originally posted by @lowzonenose in https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/310#issuecomment-2379467343_

**Comment by elias75015** [comment]
Erreur de ma part. Reporté à S11
