### ISSUE TITLE
Recette : #26 Widget de centrage sur territoire

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#316]
Recette #26 et sous-tickets :
- #70
- #71
- #72
- #73

Widget permettant de se centrer sr des territoires donnés. Paramétrable, pour l'instant la liste des territoires est la même que celle du Géoportail listée par le MousePosition.

**Comment by IGNF-Xavier** [comment]
❌  Ticket à ouvrir : inexplotaible en mobile

**71 - à vérifier :** 
❌ La Réunion n'est pas à un zoom adapté + libellé avec accent manquant
![image](https://github.com/user-attachments/assets/d4020d73-76f2-4882-9568-879a2a54460c)
❌ Faute de frappe pour la Guadeloupe
❌ Paris : le symbole correspond à Paris et Petite Couronne, le zoom est sur Paris. Il fuadrait Mettre Paris Petite Couronne et un zoom adapté
![image](https://github.com/user-attachments/assets/f72121c0-e851-4616-bc6f-18be47ccbc5c)

A challenger : ordre des territoires. Ici il est alphabétique. A mon avis, il conviendrait de mettre France et Paris Petite couronne en premier puis les collectivités d'outre-mer suivant leur numéro (et préciser en centré avec parenthèses le numéro : 971, 972, etc)
 ❌ Liste des territoires. Attention l'outremer, c'est : 
 ![image](https://github.com/user-attachments/assets/046649e3-ec97-451f-8a87-747517010d03)

✅ #72 et #73

**Comment by IGNF-Xavier** [comment]
Je remarque aussi qu'il n'y a aucun résultat qui sort quand on utilise la recherche par adresses pour les "POI" tels que la Polynésie Française ou autre

**Comment by elias75015** [comment]
Corrigé et testable dans la prochaine livraison : 
- La coche Fermer n'a pas de nom Fermer comme sur les autres widgets
- La Réunion n'est pas à un zoom adapté + libellé avec accent manquant
- Faute de frappe pour la Guadeloupe
- Paris : le symbole correspond à Paris et Petite Couronne, le zoom est sur Paris. Il fuadrait Mettre Paris Petite Couronne et un zoom adapté


Pour la liste des territoires, le widget des territoires est directement branché au fichier edito.json. Très facilement editable (à terme par la DIRCOM). Actuellement on a : 

```
territories": [
    {
      "id": "FXX",
      "title": "France métropolitaine",
      "description": "",
      "zoom": null,
      "bbox": [-9.86, 41.15, 10.38, 51.56],
      "thumbnail": ""
    },
    {
      "id": "GLP",
      "title": "Guadeloupe",
      "description": "",
      "zoom": null,
      "bbox": [-61.97, 15.72, -60.93, 16.66],
      "thumbnail": ""
    },
    {
      "id": "GUF",
      "title": "Guyane",
      "description": "",
      "zoom": null,
      "bbox": [-55.65, 1.49, -51.20, 6.21],
      "thumbnail": ""
    },
    {
      "id": "MTQ",
      "title": "Martinique",
      "description": "",
      "zoom": null,
      "bbox": [-61.40, 14.25, -60.67, 15.04],
      "thumbnail": ""
    },
    {
      "id": "REU",
      "title": "Réunion",
      "description": "",
      "zoom": 10,
      "bbox": [55.07, -21.46, 55.86, -20.79],
      "thumbnail": ""
    },
    {
      "id": "SPM",
      "title": "Saint-Pierre-et-Miquelon",
      "description": "",
      "zoom": null,
      "bbox": [-56.48, 46.69, -56.07, 47.19],
      "thumbnail": ""
    },
    {
      "id": "IDF",
      "title": "Paris petite couronne",
      "description": "",
      "zoom": 12,
      "bbox": [2.18, 48.77, 2.52, 48.95],
      "thumbnail": ""
    },
    {
      "id": "MYT",
      "title": "Mayotte",
      "description": "",
      "zoom": null,
      "bbox": [44.95, -13.049, 45.32, -12.57],
      "thumbnail": ""
    },
    {
      "id": "NCL",
      "title": "Nouvelle Calédonie",
      "description": "",
      "zoom": null,
      "bbox": [163.02,-23.08, 167.86,-19.50],
      "thumbnail": ""
    }
  ],
```
Il suffit d'éditer ce fichier pour que le widget territories se mette à jour. Il y a juste une alerte sur la longueur des titles, si c'est trop long ca peut dépasser de la case (par exemple "Paris **et** petite couronne" c'était trop long, en enlevant le "**et**" c'est bon)


>> Ticket à ouvrir : inexplotaible en mobile 

@Kristell-5 tu pourras ouvrir un ticket pour le mode mobile 

Globalement il y a toujours un sujet sur l'affichage des widgets en mode mobile, il faudrait qu'on décide d'un fonctionnement par défaut qu'on puisse implémenter sur tous les widgets (ex. "ca prend toute la page quand on ouvre un widget en mode mobile"), et qu'on adapte ce fonctionnement aux cas particuliers.

**Comment by elias75015** [comment]
Correctifs des points suivants testables sur  https://ignf.github.io/cartes.gouv.fr-entree-carto/ : 

>     - La coche Fermer n'a pas de nom Fermer comme sur les autres widgets
>     - La Réunion n'est pas à un zoom adapté + libellé avec accent manquant
>     - Faute de frappe pour la Guadeloupe
>     - Paris : le symbole correspond à Paris et Petite Couronne, le zoom est sur Paris. Il fuadrait Mettre Paris Petite Couronne et un zoom adapté


Pour les autres points : 
- mode mobile : ticket à créer
- liste et définition des territoires : à challenger, éditable très facilement, à terme sans relivraison du portail, via un fichier edito distant.

**Comment by IGNF-Xavier** [comment]
edge comme firefox: 
✅ La coche Fermer n'a pas de nom Fermer comme sur les autres widgets
✅  La Réunion n'est pas à un zoom adapté + libellé avec accent manquant
✅  Faute de frappe pour la Guadeloupe
✅  Paris : le symbole correspond à Paris et Petite Couronne, le zoom est sur Paris. Il fuadrait Mettre Paris Petite Couronne et un zoom adapté

❌ nouveau bug détecté : https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/335

**Comment by elias75015** [comment]
Nouvelle proposition : plein écran en mode mobile pour qu'il soit utilisable  : https://github.com/IGNF/geopf-extensions-openlayers/pull/184


A noter, petit changement de comportement : cliquer sur un territoire centre la carte ET ferme la modale (utile en mode mobile pour comprendre que le clic a eu une action)

**Comment by elias75015** [comment]
@IGNF/cartes-gouv-fr-entree-carto-recette à tester sur https://ignf.github.io/cartes.gouv.fr-entree-carto/

Le widget des territoires à tester sur petit écran.

Le #335 est traité de manière plus général. 

La liste des territoires sera à configurer via le fichier edito.json qui sera déposé en annexe de la GPF et qui permettra une mise à jour à la volée du widget en prod.

**Comment by IGNF-Xavier** [comment]
✅ Sur petit écran, cela fonctionne

A voir à terme que le zoom sur territoire soit réalisé en fonction de la taille de l'écran. Paris petite couronne sur mobile ne couvre même pas Paris

**Comment by quentinpage** [comment]
ok pour firefox mais le widget "territoire" ne se ferme pas avec le bouton "fermer ou la croix" du widget (version 115.7.0esr de firefox)
ok pour edge

comme indiqué plus haut pas de widget pour android (smartphone)

**Comment by IGNF-Xavier** [comment]
@quentinpage nous savons que firefox ESR 115 est problématique.
Nous devrons mettre une information indiquant la version supportée et excluant l'ESR115

**Comment by elias75015** [comment]
OK je ferme.

Pour l'emprise des territoires sur petit écran, ticket ouvert côté ext : https://github.com/IGNF/geopf-extensions-openlayers/issues/194

**Comment by quentinpage** [comment]
oui je sais que la version 115 est problématique mais mon pc avec la bonne version était indisponible ce matin. l'ordinateur en libre service n'a que cet version et d'autre fenêtre pouvaient avec cet version.
