### ISSUE TITLE
Recette : #52 #51 Widget de recherche de couches du catalogue

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#317]
Recette du #52 et #51 et sous-tickets : 
- #109
- #111
- #113

Catalogue branché construit à partir de toutes les couches de la GPF triées en dur + fichier editorial à compléter.

**Comment by IGNF-Xavier** [comment]
❌ Couche supprimée dans le layerswitcher mais reste cochée dans la recherche de couche de catalogue : 
![image](https://github.com/user-attachments/assets/a8ec0657-d4bd-42c9-93e2-1f988818cd04)

**Comment by IGNFhc** [comment]
corrigé dans cette PR
https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/328

**Comment by elias75015** [comment]
Correctif sera disponible dans la prochaine livraison.

**Comment by elias75015** [comment]
Au passage, cette PR #330 propose une version plein écran sur petit écran pour les menus de gestion des widgets et du catalogue (actuellement inutilisables en mode mobile)

**Comment by elias75015** [comment]
Correctif testable sur : https://ignf.github.io/cartes.gouv.fr-entree-carto/
