### ISSUE TITLE
Recette : #63 Partage de carte via permalien ou iframe

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#318]
Recette du #63 et sous-tickets : 
- #145
- #146
- #147
- #148

**Comment by IGNF-Xavier** [comment]
- [ ] Mineur - Design à réviser . Je m'attendais à pouvoir facilement copier le lien à côté du lien, le bouton est peut-être au mauvais endroit

**Comment by elias75015** [comment]
OK attribué à @IGNFhc  pour faire une proposition d'ergonomie sur la copie et analyse des problèmes sur les points suivants : 
- La copie par le bouton copier le lien ne copie pas le lien permanent
- A priori tous les boutons de partage ne sont pas fonctionnels (Linkedin ne fonctionne pas)
Iframe non vérifiée
- Le bouton de partage par courriel n'est pas fonctionnel. Le courriel ouvert envoie juste un mail à gé[oplateforme@ign.fr](mailto:oplateforme@ign.fr) et ne contient pas le permalien dans le corps du texte

**Comment by elias75015** [comment]
@IGNF/cartes-gouv-fr-entree-carto-recette à tester sur https://ignf.github.io/cartes.gouv.fr-entree-carto/


Corrigé : 
- Mineur - Design à réviser . Je m'attendais à pouvoir facilement copier le lien à côté du lien, le bouton est peut-être au mauvais endroit
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/147 à vérifier
- La copie par le bouton copier le lien ne copie pas le lien permanent, c'est normal
- Le bouton de partage par courriel n'est pas fonctionnel. Le courriel ouvert envoie juste un mail à gé[oplateforme@ign.fr](mailto:oplateforme@ign.fr) et ne contient pas le permalien dans le corps du texte
- Partage par Twitter

Reste à faire consigné dans ticket https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/340 : 
-  LinkedIn et Facebook : ouvre la fenêtre de partage, mais il n'y a pas de permalien dans le contenu 🟡
- Instagram : ouvre la page IGN France (a priori on fera pas meiux, à creuser) 🟡
- iframe : il manque les widgets ajoutés à la carte 🟡

**Comment by IGNF-Xavier** [comment]
✅  Mineur - Design à réviser . Je m'attendais à pouvoir facilement copier le lien à côté du lien, le bouton est peut-être au mauvais endroit
❌  J'ai copié le lien  avec le fouton et ça ne renvoie pas du tout là où était ma carte et mon pointeur
Le lien obtenu : https://ignf.github.io/cartes.gouv.fr-entree-carto?c=2.5479878714752027,50.800781249995744&z=12&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;1;0)&w=OverviewMap,SearchEngine,ScaleLine,LayerSwitcher,Legends,Isocurve,Zoom,Route,FullScreen,MeasureLength,MeasureArea,MeasureAzimuth,Share,MousePosition,Territories&permalink=yes

❌ Le lien dans le mail n'est pas cliquable
✅  Partage par Twitter

Il serait quand même pas mal d'avoir une tinyURL partagée

**Comment by quentinpage** [comment]
attention il y a une différence entre le "lien permanent vers la carte" et le lien vers les données dans "copiez le code HTML ...". les deux URL ne sont vraiment pas centrées sur le même lieux, l'un est proche du lien que l'on souhaite partagé (celui dans "le code pour HTML") le premier est situé dans le golf de guinée(https://ignf.github.io/cartes.gouv.fr-entree-carto?c=0,0%26z=5%26l=GEOGRAPHICALGRIDSYSTEMS.SLOPES.MOUNTAIN$GEOPORTAIL:OGC:WMTS(1;1;0),FORETS.PUBLIQUES$GEOPORTAIL:OGC:WMTS(1;1;0),GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;1;0)%26w=OverviewMap,SearchEngine,ScaleLine,LayerSwitcher,Legends,MeasureArea,MeasureAzimuth,Isocurve,Route,Share%26permalink=yes))
![Image](https://github.com/user-attachments/assets/2a431791-e8dc-49d7-9344-8fde656da3d9)


ticket 145
nok pour firefox. le lien fourni n'est pas centré sur l'emplacement lors de la demande de partage. elle est déplacé vers le sud 
"https://ignf.github.io/cartes.gouv.fr-entree-carto/embed?c=5.486795,43.589214&z=10&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(;1),ORTHOIMAGERY.ORTHOPHOTOS$GEOPORTAIL:OGC:WMTS(1;1;0),GEOGRAPHICALGRIDSYSTEMS.SLOPES.MOUNTAIN$GEOPORTAIL:OGC:WMTS(1;1;0)&m=&i=false&t=&g=false&permalink=yes"
alors que la demandé est centrée sur "venelles" (Bouche-du-Rhône). la conservation des couches n'est aussi pas conservée (seule la premier couche est conservée) mais pas l'agrandissement qui est augmenté
nok pour android smartphone. le lien fourni n'est pas centré sur l'emplacement lors de la demande de partage ainsi que pour les différentes couches et l'agrandissement
nok pour edge idem

ticket 146
ok pour firefox, il est possible d'accéder directement à url de la carte qui peut ainsi être modifiée (notamment pour l'emprise =centre de la carte (l)+agrandissement(z))
ok pour edge idem
ok pour android smartphone bien que plus difficile car il faut passer pour un outil de "presse papier"

ticket 147
nok la localisation n'est pas partageable, pour tous les environnement on n'est pas au "bonne" endroit (voir réponse ticket 145).

ticket 148
nok pour firefox, il n'y a pas de prévisualisation pour le partage
nok pour edgr, il n'y a pas de prévisualisation pour le partage
android n'est pas concerné par une prévisualisation

**Comment by elias75015** [comment]
" J'ai copié le lien avec le fouton et ça ne renvoie pas du tout là où était ma carte et mon pointeur
Le lien obtenu : https://ignf.github.io/cartes.gouv.fr-entree-carto?c=2.5479878714752027,50.800781249995744&z=12&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;1;0)&w=OverviewMap,SearchEngine,ScaleLine,LayerSwitcher,Legends,Isocurve,Zoom,Route,FullScreen,MeasureLength,MeasureArea,MeasureAzimuth,Share,MousePosition,Territories&permalink=yes"

--> c'est corrigé, merci JP

Quentin, pour tes remontées, je vais les analyser et les consigner dans le reste à faire sur ce widget (https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/340)
