### ISSUE TITLE
Recette : #59 Sauvegarde des paramètres de la carte dans la session

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#319]
Recette #59 et sous-tickets : 
- #260
- #262
- #264

**Comment by IGNF-Xavier** [comment]
✅ #260 Permalien fonctionnel. Néanmoins : 

- [ ] Question - Pas de conservation du symbole point de géolocalisation 
- [ ] Mineur - Design à réviser . Je m'attendais à pouvoir facilement copier le lien à côté du lien, le bouton est peut-être au mauvais endroit

✅#262 et #264

**Comment by elias75015** [comment]
@lowzonenose evol pour conserver les markers ?

**Comment by elias75015** [comment]
Ticket #332 créé. Je ferme, le reste étant validé.
