### ISSUE TITLE
Clic gauche FC-10

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#32]
FC-10

Clic gauche :  
Actuellement le clic gauche est réservé au  getFeatureInfo » sur les couches où la fonctionnalité est activée : une pop-up s'ouvre et affiche les informations attributaires de (ou des) élément(s) cliqué(s) de (ou des couches) sous le pointeur de la souris. 

> **A déterminer** : évolutions qui n’ont pas encore été travaillées et développées 

**Questions** 

*Un pop-up doit s’afficher ? Où et avec quel style (modale DSFR ?) ?*
Au plus proche du clic en restant visible dans la fenêtre 
Style au DSFR (modale DSFR) 
https://6tapsu.axshare.com/#g=1&p=portail_carto_-_clic_gauche

**Comment by Kristell-5** [comment]
modale dsfr

**Comment by elias75015** [comment]
Maquette disponible sur le Figma. A implémenter pour la V1 si possible.

**Comment by elias75015** [comment]
En cours de finalisation par Hector sur les extensions. Certainement intégrable à l'entrée carto dans les deux prochaines semaines pour une validation + livraison prod avant le sprint S8.
