### ISSUE TITLE
Recette : #279 Mise en place des remontées stats Eulerian

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#320]
Recette #279 : Première mise en place des remontées statistiques des interactions utilisateurs

Ne prend pas en compte l'amélioration du paramètrage des remontées qui sera traitée dans #178 et #280

**Comment by IGNF-Xavier** [comment]
J'ai bien la modale d'autorisation de stats Eulerian.
Je clique sur accepter, je la trouve un peu longue à fermer

**Comment by elias75015** [comment]
Je ferme, le reste sera traité dans #178 et #280
