### ISSUE TITLE
Recette : #242 #289 #306 Correctifs amélioration ergonomie header / footer

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#321]
Recette des tickets : 
- #242
- #289
- #306

Divers bug ou problèmes ergonomiques grossiers en lien avec la structure de la page (header + footer) corrigés

**Comment by IGNF-Xavier** [comment]
❌ les boutons sont au-dessus du résultat de la recherche
![image](https://github.com/user-attachments/assets/d5ba1442-e1db-4af1-b11c-125da29a6f55)

❌ l'espace de l'écran n'est pas optimisé #289 un blanc reste sous les paramètres d'affichage
![image](https://github.com/user-attachments/assets/b2e9ec86-c51c-448b-84c9-85b414cf3016)

✅ #306

**Comment by elias75015** [comment]
Testable sur la page de démo https://ignf.github.io/cartes.gouv.fr-entree-carto. Les changements sont directement listés dans #330

**Comment by IGNF-Xavier** [comment]
✅ Proposition temporaire de réorganisation des boutons sur petits écrans.
✅ Réadaptation de la hauteur de la carto quand le footer est réduit sur petit écran.

✅ #330
