### ISSUE TITLE
Recette #290 : Ajustement sur la taille du panel des légendes

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#331]
Recette du ticket #290

**Comment by IGNF-Xavier** [comment]
Firefox : Ok
Edge : OK
Certes la taille est plus grande.
Je m'attendais plutôt à quelque chose de plus dynamique en fonction de la taille de la fenêtre.

A travailler pour le mobile de manière générale. @elias75015 y- a t(il un ticket chapeau qui identifierait les constats faits sur mobile?
 
Le ticket peut-être fermé pour les tailles au-dessus du pont de rupture

**Comment by elias75015** [comment]
Je ferme.

On a décidé ce matin d'une solution à court terme pour affichage des panels selon les différentes tailles d'écran, quand on commencera à travailler dessus la semaine prochaine
