### ISSUE TITLE
Gestion de l'ordre d'affichage des modales - superposition

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#335]
### Description

Les modales se superposent mais pas forcément dans l'ordre demandé.

### Comportement attendu

Ordre des modales à respecter

### Comment reproduire l'anomalie

1- cliquer sur position curseur : la modale apparait
2- cliquer sur le centrage territoire : la modale apparait en-dessous alors que c'est la 2e appelée qui doit appraitre au-dessus.

Dans tous les cas, c'est toujours coordonnées qui est audessus. Ce n'est pas normal

**Comment by elias75015** [comment]
OK il y a un sujet à investiguer, pour l'instant l'ordre est fixe. Il faudrait que la dernière modale cliquée ait un index = index max + 1 par rapport aux autres modales.

@lowzonenose si tu peux regarder ?

**Comment by elias75015** [comment]
@IGNF-Xavier @Kristell-5  est-ce qu'implémenter le comportement un panel ouvert ferme un autre panel ouvert (un seul widget ouvert en même temps) vous parait pertinent dans un premier temps ? Sinon c'est un peu prise de tête à court terme.

On peut éventuellement faire en sorte de faire des exceptions s'il est pertinent que deux widgets soient ouverts en même temps.

**Comment by elias75015** [comment]
OK on va faire comme ça alors : un panel par côté.

En mode mobile (petit écran), on limite en revanche à un seul panel autant que faire se peut en plein écran.

**Comment by lowzonenose** [comment]
On tente une mise en place du coté des extensions.
