### ISSUE TITLE
Modifier les liens du footer (gouvernement.fr / info.gouv.fr)

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr-entree-carto#336]
Les liens doivent être dans l'ordre :

* info.gouv.fr (nouveau nom de gouvernement.fr)
* service-public.fr
* legifrance.gouv.fr
* data.gouv.fr

Voir https://github.com/IGNF/cartes.gouv.fr/issues/367 (briques alimentation et catalogue sont à jour)

**Comment by elias75015** [comment]
Corrigé sur https://ignf.github.io/cartes.gouv.fr-entree-carto/

Dispo dans la prochaine livraison en prod
