### ISSUE TITLE
Centrage par permalien cassé

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#342]
❌ J'ai copié le lien avec le fouton et ça ne renvoie pas du tout là où était ma carte et mon pointeur
Le lien obtenu : https://ignf.github.io/cartes.gouv.fr-entree-carto?c=2.5479878714752027,50.800781249995744&z=12&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;1;0)&w=OverviewMap,SearchEngine,ScaleLine,LayerSwitcher,Legends,Isocurve,Zoom,Route,FullScreen,MeasureLength,MeasureArea,MeasureAzimuth,Share,MousePosition,Territories&permalink=yes

**les coordonnées du centre du permalien sont désormais écrits en géographiques --> La carto doit se centrer en 4326"

**Comment by lowzonenose** [comment]
:green_circle: corrigé !
