### ISSUE TITLE
prioriser les wmts dans la recherche de couches

### ISSUE THREAD

**Issue by vbrinon** [IGNF/cartes.gouv.fr-entree-carto#355]
### Le besoin que vous rencontrez

Lorsqu'on cherche une couche sur cartes.gouv, cela retourne les WMSV.

Ça serait mieux d'avoir les WMTS en priorité pour ne pas solliciter les BDD et les geoserver et profiter des pyramides images créées.

**Comment by elias75015** [comment]
Correctif côté extensions à monter sur l'entrée carto

**Comment by elias75015** [comment]
@vbrinon tu peux tester sur https://ignf.github.io/cartes.gouv.fr-entree-carto/ et nous dire si ça convient à môsieur ?

**Comment by vbrinon** [comment]
C'est parfait cher @elias75015
