### ISSUE TITLE
Recette #358 : ajout tooltip aux boutons

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#362]
Recette du #358 : au survol de la souris ou navigation clavier sur les boutons, un tooltip avec le titre du bouton apparait immédiatemment

**Comment by IGNF-Xavier** [comment]
- [ ] Non bloquant : remplacer "Selecteur de territoire" par "Sélecteur de territoire"
- [ ] Non bloquant : remplacer "Activer la geolocalisation" par "Activer la géolocalisation"
- [ ] Non bloquant : @Kristell-5 , ne devrait-pas remplacer "Ouvrir le panneau de partage de carte" par "Partager la carte"? 
- [ ] Non bloquant : @Kristell-5 , ne devrait-pas remplacer "Ouvrir la recherche par coordonnées" par "Rechercher par coodonnées"? 
- [ ] Non bloquant : Sur Edge, valider le comportement double étiquette 
![image](https://github.com/user-attachments/assets/78e69095-5303-4611-8376-1cc8cb5357a0)

**Comment by elias75015** [comment]
Pour la double étiquette, un ticket existe côté extensions :
https://github.com/IGNF/geopf-extensions-openlayers/issues/239

On va essayer de le traiter rapidement. A priori ce n'est pas que sur Edge.

Pour les accents manquants on corrige ça rapidement

**Comment by elias75015** [comment]
Pour la double étiquette, normalement c'est corrigé côté extensions, à retester.

Le problème persiste sur les boutons menu widgets, menu catalogue et partage (https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/374) car implémenté côté entrée carto.

Au passage, les accents manquants sur "Géolocalisation" et "Sélecteur" ont été ajoutés.

**Comment by IGNF-Xavier** [comment]
✅ Corrigé sur Edge sauf menu catalogue, widgets et partage
🆕 Tooltip carte générale masqué par échelle

**Comment by elias75015** [comment]
>  🆕 Tooltip carte générale masqué par échelle

Ticket https://github.com/IGNF/geopf-extensions-openlayers/issues/248

Non bloquant ?

**Comment by quentinpage** [comment]
ok pour firefox 128.3.1
ok pour edge 130.0.2849.56
ok pour chrome 130.0.6723.92
pas réalisable sur android smartphone

remarque : le texte du bouton "carte général" 'en bas et à gauche est caché partiellement par la légende cartographique mais le bouton conctionne

**Comment by elias75015** [comment]
OK merci, le ticket https://github.com/IGNF/geopf-extensions-openlayers/issues/248 indique le RAF. Je ferme
