### ISSUE TITLE
Recette #351 #344 #336 : amélioration conformité DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#363]
Recette #351 #344 #336 : Amélioration conformité DSFR avec passage des boutons carto en secondaires, marker de positionnement en mode DSFR et mise en conformité des liens dans le footer

**Comment by IGNF-Xavier** [comment]
✅ #351 
Non bloquant #344 au clic, il y a une pop-up avec écrit "Sans information". @Kristell-5 : 
- A  supprimer?
- A compléter avec mention "Votre position" voire enrichi avec les coordonnées lat/long (pour des questions d'accessibilité)

✅ #336

**Comment by elias75015** [comment]
"A compléter avec mention "Votre position" voire enrichi avec les coordonnées lat/long (pour des questions d'accessibilité)"

OK je note dans un ticket (https://github.com/IGNF/geopf-extensions-openlayers/issues/244), faisable simplement normalement.

**Comment by IGNF-Xavier** [comment]
Je propose donc de fermer ce ticket et réouvrir un ticket recette quand #244 réalisé
