### ISSUE TITLE
Recette #265 #266 #349 #356 : améliorations gestion des paramètres de session

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#364]
Recette #265 #266 #349 #356 :
- ajout d'une clé partagée entre les différentes briques de cartes.gouv pour conserver le choix du thème (sombre/light)
- ajout d'une clé partagée entre les différentes briques de cartes.gouv pour conserver le choix du consentement (eulerian)
- ajout d'une clé pour versionner le localStorage et ainsi ne pas avoir de problème lors d'une relivraison (o force le localStorage à se vider s'il y a eu des breaking changes dessus)

**Comment by elias75015** [comment]
Tout à fait il n'y a pas eu de breaking changes sur le localStorage dans cette livraison 1.0.1, donc on ne le réinitialise pas !

**Comment by quentinpage** [comment]
ok pour la conservation des thèmes, des couches, des outils et du choix des cookies pour chrome (le nom de la clé est "transparente")
ok pour la conservation des thèmes, des couches, des outils et du choix des cookies pour edge (le nom de la clé est "transparente")
ok pour la conservation des thèmes, des couches, des outils et du choix des cookies pour firefox (le nom de la clé est "transparente") mais la non acceptation des cookies n'a pas été testé
ok pour la conservation des thèmes, des couches, des outils et du choix des cookies pour android smartphone (le nom de la clé est "transparente") mais la non acceptation des cookies n'a pas été testé

remarque: le temps de l'acceptation des cookies est un peu longue quelque secondes
