### ISSUE TITLE
Recette #32 : Widget de getFeatureInfo

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#369]
Recette #32 : ajout première version du widdget de getFeatureInfo

**Comment by IGNF-Xavier** [comment]
❌ Mineur - Modale à améliorer. Présence d'ascenseurs inutiles
![image](https://github.com/user-attachments/assets/a7442bc1-2b82-41c3-8833-24d175309b89) 
❌ Mineur - le terme getfeatureinfo est à changer (@Kristell-5 , terme à trouver)

**Comment by elias75015** [comment]
@IGNFhc tu pourras vérifier stp ?

**Comment by elias75015** [comment]
2 tickets créés, je ferme

https://github.com/IGNF/geopf-extensions-openlayers/issues/253

https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/381
