### ISSUE TITLE
Recette #355 : Amélioration filtrage barre de recherche

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#371]
Recette #355 :  rechercher une couche disponible en WMTS ET WMS sort en priorité la couche WMTS

**Comment by IGNF-Xavier** [comment]
✅ Ok pour l'ordre de priorité.

2 questions cependant : 
- Ne devrait-on pas reconnaitre le type de service utilisé ?
- Ne devrait-on pas "filtrer" le résultat du moteur de recherche en n'affichant que le WMTS s'il existe et pas le WMS?

**Comment by elias75015** [comment]
@lowzonenose il me semble qu'il y avait un blocage pour le second point ?

**Comment by elias75015** [comment]
https://github.com/IGNF/geopf-extensions-openlayers/issues/254 créé, je ferme
