### ISSUE TITLE
Recette #311 : éléments par défaut sur l'interface

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#372]
Recette #311 : Plan IGN par défaut + Layerswitcher et barre de recherche comme widgets fixes sur l'interface

**Comment by IGNF-Xavier** [comment]
✅ Plan IGN par défaut
✅ Barre de recherche et layerswitcher fixe
❌ Mineur ou pour plus tard : les boutons fixes avec la recherche de lieu semble ne pas être bien positionné
![image](https://github.com/user-attachments/assets/72217667-08f6-42e0-b303-3edb88bc60ba)

**Comment by elias75015** [comment]
C'est volontaire sur petit écran pour optimiser la place, mais de toute manière ca va changer (en attente maquette suite à l'atelier du 28/10)

**Comment by quentinpage** [comment]
ok pour firefox, il y a bien "plan IGN V2" par défaut ainsi que la barre de recherche et le layerswitcher
ok pour chrome, il y a bien "plan IGN V2" par défaut ainsi que la barre de recherche et le layerswitcher
ok pour edge, il y a bien "plan IGN V2" par défaut ainsi que la barre de recherche et le layerswitcher

non tester sur android smartpone, la suppression des cookies n'a pas été réalisé sur mon smartphone personnel donc le comportement par défaut n'a pas pu être réalisé

**Comment by elias75015** [comment]
OK merci je ferme car RAS de plus
