### ISSUE TITLE
LocalStorage et controls disponibles

### ISSUE THREAD

**Issue by IGNFhc** [IGNF/cartes.gouv.fr-entree-carto#377]
### Description

Lorsqu'on désactive un control il reste disponible si l'utilisateur l'avait activé avant la mise à jour du site.

### Comportement attendu

Lorsqu'on désactive un control, il est supprimé du lcoalstorage de l'utilisateur

### Comment reproduire l'anomalie

désactiver un control côté dev qui est activé côté interface

### Solution possible

filtré au moment de la récupération des control du local storage ceux qui sont actifs

**Comment by lowzonenose** [comment]
Pour info
si **break change** au niveau du _localStorage_ (modification de l'impl. du mapStore ou appStore), on force la réinitialisation des clients en incrémentant la version du _localStorage_.
cf. https://github.com/IGNF/cartes.gouv.fr-entree-carto/blob/388df92c5ee761326f3c5f0d2f0e35965f688005/src/stores/appStore.js#L21

On ferme ?
