### ISSUE TITLE
Enlever widgets obligatoires du permalien

### ISSUE THREAD

**Issue by azarz** [IGNF/cartes.gouv.fr-entree-carto#400]
Un certain nombre de widgets sont obligatoires. Il faut les enlever du permalien.

**Comment by elias75015** [comment]
Permalien si je désactive TOUS les widgets optionnels : http://localhost:5173/cartes.gouv.fr-entree-carto?c=2.167946404636789,49.44765389070585&z=13&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;1;0)&w=OverviewMap,SearchEngine,ScaleLine,LayerSwitcher,GetFeatureInfo,Legends,Zoom,FullScreen,MeasureArea,Share,Territories,ControlList&permalink=yes


Problèmes : 
- le permalien est long est pourrait être réduit en enlevant les widgets ajoutés par défaut à la carto
- si j'édite le permalien, et que j'enlève un widget obligatoire, je peux charger une carto sans ce widget. Exemple (j'enlève la barre de recherche) : http://localhost:5173/cartes.gouv.fr-entree-carto?c=2.167946404636789,49.44765389070585&z=13&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;1;0)&w=OverviewMap,ScaleLine,LayerSwitcher,GetFeatureInfo,Legends,Zoom,FullScreen,MeasureArea,Share,Territories,ControlList&permalink=yes

**Comment by elias75015** [comment]
Et effet de bord supplémentaire après avoir cliqué sur le deuxième permalink mis en exemple au dessus : Aucun moyen de retrouver la bare de recherche à moins de vider son localStorage

**Comment by elias75015** [comment]
🤯 un peu une usine à gaz la gestion localStorage / permalink.

- ajouter des getters sur les controls pour récupérer les controls actif optionnels, les controls actifs obligatoires, tous les controls...
- trouver une nomenclature plus explicite : on ne sait pas à quoi "active" ou "disable" correspond exactement
- peut être complexifier la propriété controls du localStorage pour avoir les controls optionnels séparés des controls obligatoires

**Comment by lowzonenose** [comment]
On peut enlever les contrôles obligatoires du permalien, mais on doit toujours garder une cohérence entre les contrôles du localStorage et la carte. Donc, on rajoute les contrôles obligatoire dans le localStorage.
