### ISSUE TITLE
Recette #313, #400 : fix sur le permalien

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#413]
#313 

Je modifie l'ordre des couches.
Sans déplacer la carte, je copie colle le permalien.
--> La vue se charge avec les couches dans le bon ordre.

#400 

Je clique sur ce permalien qui n'a aucun widget configuré (w=&) : https://ignf.github.io/cartes.gouv.fr-entree-carto/?c=3.7976536570039725%2C51.275062192131514&z=8&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2%24GEOPORTAIL%3AOGC%3AWMTS%281%3B1%3B0%29&w=&permalink=yes

--> La vue se charge avec les widgets par défaut (overview, searchengine, layerswitcher, legends...)

**Comment by quentinpage** [comment]
**### _pour firefox 128.3.1esr:_**
lors de la création d'une carte avec plusieurs couches, l'affichage de la carte se différencie selon l'ordre des couches.
le "bouton " "partager une carte" fournit 2 url (surlignage jaune et contour rouge de la figure "captureLienDesCarte.png".
![Image](https://github.com/user-attachments/assets/a31a9e98-86c8-41e6-be02-323467aec4ae)

Ces URL aussi bien "lien permanent" que le lien "src" donne bien des cartes si on place ces url dans le navigateur mais si on modifie après l'ordre des couches ou que l'on modifie la transparence d'une couche. ces url ne modifie pas l’ordre ou la transparence des couches qui ont été modifiées. ce lien n'est d’ailleurs pas changé dans le bouton "partager une carte". cf le lien i dessous

https://ignf.github.io/cartes.gouv.fr-entree-carto/embed?c=3.081468989230366,50.60806226520259&z=11&l=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2$GEOPORTAIL:OGC:WMTS(1;0;0),ORTHOIMAGERY.ORTHOPHOTOS$GEOPORTAIL:OGC:WMTS(1;1;0),BESOIN.CHALEUR.TERTIAIRE$GEOPORTAIL:OGC:WMTS(1;1;0)&permalink=yes
![Image](https://github.com/user-attachments/assets/d00744c0-6b6c-4718-9cbc-a4d552a24bc9)


**### _pour chrome 131.0.6778.139**
ce même comportement est observé.


**### _pour edge131.0.6778.139**
ce même comportement est observé sauf que le lien dans "partagé une carte" est mis à jour.



**### _pour android pour smartphone**
pas concerné

**Comment by elias75015** [comment]
Pas certain de bien comprendre...après de multiples tests de mon côté je ne vois pas ce qui dysfonctionne.

Peut être l'OS ? Quelqu'un d'autre sous Windows pourrait-il tester svp @Kristell-5 @IGNF-Xavier  ?

**Comment by Kristell-5** [comment]
Je ne suis pas une spécialiste des tests, mais pour moi, quand je change l’opacité, l’affichage du lien s’actualise.

**Comment by IGNF-Xavier** [comment]
A clore
