### ISSUE TITLE
Recette #64 : première version de la fonction print

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#414]
#64 

Le bouton print est en haut à droite activable via le menu des widgets pour l'instant.
-> tester l'impression

Reste à faire :
- l'intégrer au menu des fonctionnalité tierces
- pouvoir ajouter un titre et une description à son impression

**Comment by quentinpage** [comment]
il manque aussi l'indication de l’échelle et de la légende (même si la légende n'a pas été demandé, la légende est obligatoire pour une carte).

pour firefox 128.3.1esr
ok "l'impression" est bien un outil qui est disponible sur un bouton en haut à droite. ce bouton fonctionne sous un export pdf. l'emprise dépend bien du choix du format, Le parti pris de conserver l’échelle (non indiqué) est bien pris en compte en changeant l'emprise. le passage du format "paysage" ou "portrait" change bien l'emprise.
mais  il est seulement possible de réaliser une "impression" virtuel (format pdf). le site ne parcours pas la liste des impressions disponibles.

pour chrome 131.0.6778.139
ok pour chrome.
le comportement est le même que pour firefox
sauf qu'il est impossible de données nom ou un lieu d'enregistrement de la carte.

pour edge 
ok pour edge
le comportement est le même que pour firefox
sauf qu'il est impossible de données nom ou un lieu d'enregistrement de la carte.


pour android smartphone
ok le bouton n’apparait pas, ce qui est normale pour la taille de l'écran et la situation d'utilisation.

**Comment by IGNF-Xavier** [comment]
Sur les dimensions, le comportement est assez bizarre, notamment avec le A0 et le chargement de milliers de tuiles.

**Comment by elias75015** [comment]
> Sur les dimensions, le comportement est assez bizarre, notamment avec le A0 et le chargement de milliers de tuiles.

Si je ne m'abuse, c'est pour répondre au besoin d'impression "haute définition". C'est la contrepartie qui permet d'avoir une impression de qualité (pas floue) quelque soit le format choisi. @IGNFhc tu confirmes ?



> il manque aussi l'indication de l’échelle et de la légende (même si la légende n'a pas été demandé, la légende est obligatoire pour une carte).

@IGNFhc possibilité d'ajouter l'echelle sur l'impression ? Oubli de ma part, je me vois pas pousser en prod sans l'echelle, même si la fonctionnalité est encore vouée à évoluer. 

Pour la légende c'est plus compliqué, et ce n'était pas sur le Géoportail, donc pas de régression à ce niveau là. On garde pour plus tard 👍

**Comment by Kristell-5** [comment]
D’un point de vue UI (et peut-être lié à ma machine), l’espace autour de la carte pourrait-il être réduit ?
![Image](https://github.com/user-attachments/assets/949b8a22-dc57-47f7-8aff-3ac942319298)

**Comment by IGNFhc** [comment]
> D’un point de vue UI (et peut-être lié à ma machine), l’espace autour de la carte pourrait-il être réduit ? ![Image](https://github.com/user-attachments/assets/949b8a22-dc57-47f7-8aff-3ac942319298)

ok je prend en compte pour réduire la taille de la modal !

**Comment by IGNF-Xavier** [comment]
La réduction de la modale ne me parait pas bloquante pour la livraison.

**Comment by IGNF-Xavier** [comment]
Ok. A clore
