### ISSUE TITLE
Recette #22 : première version du widget de dessin

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#415]
#22 

Le widget de dessin est activable et fonctionnel.

Reste à faire : 

Travail UI pour améliorer le rendu, maquettes en cours.

**Comment by quentinpage** [comment]
pour firefox
l'outil d'annotation côté création
*le polygone est bien créé mais on ne voit pas le texte de l'annotation et quand on ferme la fenêtre sans enregistrer le polygone, le polygone reste sur la carte.
*la ligne est bien créée mais on ne voit pas le texte de l'annotation et quand on ferme la fenêtre sans enregistrer la ligne, elle reste sur la carte.
*le point est bien créée mais on ne voit pas le texte de l'annotation et quand on ferme la fenêtre sans enregistrer le point, il reste sur la carte.
*le texte est bien créée et on le voit la carte, il est cependant impossible de choisir la couleur du texte.
l'outil d'annotation côté édition
*il n'y a pas moyen de "sélectionner" les objets.
des essais ont été tenté:
*que la couche croquis d'ouvert puis cliqué sur les objets avant ou après "modifier l’apparence des objet" ou "editer les tracés"
*que la couche croquis d'ouvert puis cliqué sur le bouton "getfeatureinfo" en bas à gauche : réponse "undefined"

pour chrome
le comportement est le même que celui de firefox

pour edge
l'outil d'annotation côté création
*le polygone est bien créé mais on ne voit pas le texte de l'annotation et quand on ferme la fenêtre sans enregistrer le polygone, le polygone reste sur la carte.
*la ligne est bien créée mais on ne voit pas le texte de l'annotation et quand on ferme la fenêtre sans enregistrer la ligne, elle reste sur la carte.
*le point est bien créée mais on ne voit pas le texte de l'annotation et quand on ferme la fenêtre sans enregistrer le point, il reste sur la carte.
*le texte est bien créée et on le voit la carte, il est cependant impossible de choisir la couleur du texte.
l'outil d'annotation côté édition
*il n'y a pas moyen de "sélectionner" les objets.


pour android smartphone
le comportement semble identique mas l'utilisation de cette outil est très difficile vu la taille de l'écran.

**Comment by elias75015** [comment]
Il faut au préalable activer le widget de getFeatureInfo.

Nous allons l'activer par défaut, ce sera plus clair pour l'utilisateur.

Problème sur le titre et le zoomToExtent aussi corrigé par la même occasion dans cette PR en cours de review par l'équipe de dev : 

https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/422

**Comment by elias75015** [comment]
PR poussée.

Plein de corrections dessus : 
- le getFeatureInfo est activé par défaut
- les titres par défaut des couches iti/iso/croquis s'affichent dans le panel GetFeatureInfo ("Mon Itinéraire" "Mon Isochrone" "Mon Croquis")
- les titres par défaut des couches iti/iso/croquis s'affichent dans le panel LayerSwitcher ("Mon Itinéraire" "Mon Isochrone" "Mon Croquis")
- la fonctionnalité pour zoomer sur l'étendue des couches est réparée pour iti/iso/croquis

**Comment by elias75015** [comment]
A retester

**Comment by quentinpage** [comment]
firefox
ok pour obtention des info avec le getFeatureInfo 
ok pour le nom de la couche 'Mon Croquis" dans le LayerSwitcher 
ok pour la possibilité de supprimer la "couche "mon isochrone" la poubelle est là.
ok pour le zoom sur la couche
nok pour la sélection puis la modification "outils d'éditions"

edge
le comportement est le même

chrome
le comportement est le même sauf pour l'enregistrement de l'export où le site ne demande pas l'endroit et le nom du croquis mais exporte bien le croquis.

**Comment by elias75015** [comment]
Ah oui bien vu : grosse regression sur les outils d'edition (boutons du bas) de l'outil de croquis, qui ne fonctionnent plus. Regression apparue suite au merge de cette PR : https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/379


On regarde

**Comment by elias75015** [comment]
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/426

**Comment by IGNF-Xavier** [comment]
Non bloquant : 
![Image](https://github.com/user-attachments/assets/1884e7d2-174d-4965-b778-add869527dbc)

SI problème identifié dans le backlog car première version du widget, ok pour déployer:  Il faudrait que la modale apparaisse de préférence en visible entièrement avec l'objet
![Image](https://github.com/user-attachments/assets/3ad409bc-30a5-4590-be7c-13b1cc9fc6d3)

SI problème identifié dans le backlog car première version du widget, ok pour déployer: pas de bouton pour l'annotation mais la touche entrée permet de marquer l'annotation : 
![Image](https://github.com/user-attachments/assets/d86a321f-87ba-4f73-96d3-8605593f8939)


En soi, cela fonctionne mais il y aura un peu de travail sur la V2.
D'un point de vue recette, il faudra vérifier à la prochaine itération si tous les éléments du croquis sont bien exportés.

Déploiement OK avec réserves à indiquer sommairement dans le changelog

**Comment by elias75015** [comment]
Maquette déjà réalisée par Sonia, qu'on va implémenter pour améliorer le rendu.
