### ISSUE TITLE
Recette #2 #39 : tous les widgets sont au DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#416]
#2 #39 

Tous les widgets ajoutables à l'interface carto sont conformes DSFR (dans les grandes lignes). Les ajustements pourront être faits dans des tickets séparés

**Comment by quentinpage** [comment]
la fenêtre d'ajout des outils masque les outils en majorité

pour firefox
tous les 12 outils fonctionnent correctement (les DSFR8 à DSFR18 et DSFR22).
*dommage que sur les données importé DSFR12 pour une "tuile vectoriel"  il n'y a pas également de message d'erreur en cas de "mauvais fichier".
le choix pour "tuile vectoriel" et "url" ("https://data.geopf.fr/telechargement/resource/ADMIN-EXPRESS-COG" (qui donne un fichier  xml en sortie) ou (https://data.geopf.fr/wfs/ows?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&typeNames=BDCARTO_V5:troncon_de_route&outputFormat=application/json qui donne un json en soritie)) n'affiche ni une fenetre erreur ni des données.
*dommage pour isochrone (distance) que les sommets du polygone résultant peuvent être au milieu d'une zone inaccessible (champs)
*l'outil des coordonnées pour la projections Lamb93 donne des résultats sur les DOM quand on a réalisé une première recherche sur la métropole
*l'outil de calcul d'itinéraire est mal calculé pour le temps avec voiture pour l'option au plus rapide.
*l'outil isochrone ne doit pas comprendre d'option "sens du parcour" pour moi cet outil indique les" points" depuis le point choisi.
*la couche de recherche inversé ne s'efface pas et se multiplie par le nombre de recherche.
*l'outil de calcul de surface compte mal pour les polygone "papillions"

![Image](https://github.com/user-attachments/assets/5350ffb0-aa87-4155-8467-5c2b2aa8e522)
et
![Image](https://github.com/user-attachments/assets/6fc9a34b-2d4b-4f30-8cd6-1f01cc8da4b8)


pour chrome
les comportements sont similaires à firefox
les outils qui apparaissent directement à droite ne sont pas les mêmes que ceux pour firefox mais ils ont les mêmes comportements.

pour edge
les comportements sont similaires à firefox

pour android smartphone
les outils ne semblent pas apparaitre.

**Comment by IGNF-Xavier** [comment]
- [ ] **Non bloquant** mais à identifier dans le changelog : Catcher erreur -  sur les données importé DSFR12 pour une "tuile vectoriel" il n'y a pas également de message d'erreur en cas de "mauvais fichier".
- [ ] **A identifier côté dev** : le choix pour "tuile vectoriel" et "url" ("https://data.geopf.fr/telechargement/resource/ADMIN-EXPRESS-COG" (qui donne un fichier xml en sortie) ou (https://data.geopf.fr/wfs/ows?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&typeNames=BDCARTO_V5:troncon_de_route&outputFormat=application/json qui donne un json en soritie)) n'affiche ni une fenetre erreur ni des données.
- **N'est pas du ressort de l'entrée carto** : dommage pour isochrone (distance) que les sommets du polygone résultant peuvent être au milieu d'une zone inaccessible (champs)
- [ ] **Non bloquant** mais ticket mineur à ouvrir pour release suivante, amélioration à identifier dans le changelog :  l'outil des coordonnées pour la projections Lamb93 donne des résultats sur les DOM quand on a réalisé une première recherche sur la métropole
- **N'est pas du ressort de l'entrée carto** : l'outil de calcul d'itinéraire est mal calculé pour le temps avec voiture pour l'option au plus rapide.
- **Hors sujet**. Besoin utilisateur existant. l'outil isochrone ne doit pas comprendre d'option "sens du parcours" pour moi cet outil indique les" points" depuis le point choisi.
- [ ] **Non bloquant mais ticket majeur** à ouvrir pour release suivante, amélioration à identifier dans le changelog : la couche de recherche inversé ne s'efface pas et se multiplie par le nombre de recherche.
- [ ] **Non bloquant mais ticket mineur** à ouvrir pour release suivante, amélioration à identifier dans le changelog: l'outil de calcul de surface compte mal pour les polygone "papillions"


- [ ] **Smartphone :** Le bouton plus apprait et perrmet d'avoir accès aux outils. Par contre aucun bouton ne s"implémente avant le plus. Non bloquant mais ticket mineur à mettre pour une future release

Cochés : ![Image](https://github.com/user-attachments/assets/200bd4e1-72a2-4725-b457-8839227a9e2b)
Résultat : ![Image](https://github.com/user-attachments/assets/0ed634b4-b240-4856-8ef0-8443a434be8d)

**Comment by elias75015** [comment]
> * l'outil des coordonnées pour la projections Lamb93 donne des résultats sur les DOM quand on a réalisé une première recherche sur la métropole

https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/427 : ticket à détailler, notamment le scénario de reproduction


> * **Non bloquant** mais à identifier dans le changelog : Catcher erreur -  sur les données importé DSFR12 pour une "tuile vectoriel" il n'y a pas également de message d'erreur en cas de "mauvais fichier".

https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/428

> * la couche de recherche inversé ne s'efface pas et se multiplie par le nombre de recherche.

Pas certain de comprendre. Deux couches s'ajoutent : une pour la requete au service (emprise, point, cercle), une pour les résultats (ensemble des adresses/parcelles/toponymes renvoyés sous forme de ponctuel). Si je refais un calcul, ces couches sont remplacées. Si je ferme le widget de geocodage inverse, ces couches disparaissent.
![Image](https://github.com/user-attachments/assets/27d2c098-c11f-421f-8664-4c48afc3d93c)
![Image](https://github.com/user-attachments/assets/044c9fa6-9c00-465c-82e7-f42e97af98fc)


> * l'outil de calcul de surface compte mal pour les polygone "papillions"

https://github.com/IGNF/geopf-extensions-openlayers/issues/299


> * **Smartphone :** Le bouton plus apprait et perrmet d'avoir accès aux outils. Par contre aucun bouton ne s"implémente avant le plus. Non bloquant mais ticket mineur à mettre pour une future release

Comportement attendu : en mode smartphone, on affiche que les boutons des widgets obligatoire / par défaut. Tous les widgets optionnels sont accessibles par le bouton +. @Kristell-5 tu confirmes ?

**Comment by elias75015** [comment]
En attente de réponse sur ce dernier commentaire, je fermerai lundi soir, les problèmes avérés pour l'instant ayant été répertoriés dans des tickets.

**Comment by IGNF-Xavier** [comment]
Pas de confirmation mais acceptable si aujourd'hui ce n'est que le bouton +.
A vérifier si nous n'aurions pas intérêt de mettre X boutons de widgets en fonction de la taille de l'écran et de l'orientation de l'écran
