### ISSUE TITLE
Recette #387 : Bouton "+" et adaptation du nombre de boutons affichés selon hauteur de la page

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#417]
#387 

Bouton + qui permet de lister les widgets ajoutés à la carte.

**Comment by quentinpage** [comment]
pour firefox
oui le bouton existe et il permet bien d'accéder à d'autres outils

pour chrome
oui le bouton existe et il permet bien d'accéder à d'autres outils

pour edge
oui le bouton existe et il permet bien d'accéder à d'autres outils

pour android smartphone
oui le bouton existe et mais il ne permet pas d'accéder à d'autre outils.
la liste des outils apparait bien mais l'outil n'est pas lancé et il n'apparait pas sur l'espace cartographique.
