### ISSUE TITLE
Recette #385 : refactorisation de l'UX du menu de gestion des widgets

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#418]
#385 

Refactorisation de l'UX du menu de gestion des widgets

**Comment by elias75015** [comment]
@IGNFhc Tu peux regarder stp pour rapprocher le sous-titre du titre stp ? Passe par une branche "fix/recette-menu-widget-418" + PR, on y fera les éventuelles autres corrections si on a d'autres retours. Merci

**Comment by IGNFhc** [comment]
> [@IGNFhc](https://github.com/IGNFhc) Tu peux regarder stp pour rapprocher le sous-titre du titre stp ? Passe par une branche "fix/recette-menu-widget-418" + PR, on y fera les éventuelles autres corrections si on a d'autres retours. Merci

Pour ce point il faut alors modifier le composant DSFR

**Comment by elias75015** [comment]
> > [@IGNFhc](https://github.com/IGNFhc) Tu peux regarder stp pour rapprocher le sous-titre du titre stp ? Passe par une branche "fix/recette-menu-widget-418" + PR, on y fera les éventuelles autres corrections si on a d'autres retours. Merci
> 
> Pour ce point il faut alors modifier le composant DSFR

Ticket poussé sur le slack DSFR par @IGNF-Xavier : https://gouvfr.slack.com/archives/C01GEGGP3RV/p1734032433161989

Leur première réponse laisse à penser qu'ils ne feront pas évoluer le composant à court terme. Je propose de valider ce ticket de recette en attendant l'évolution du composant pour ne pas bloquer la livraison.

**Comment by IGNF-Xavier** [comment]
@elias75015 
Pas bloquant pour la livraison mais à documenter dans le changelog comme identifié.

A voir si  on a pas intérêt à mettre à gauche le toggle pour la livraison suivante si pas corrigeable à la volée

**Comment by elias75015** [comment]
Consigné ici : https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/429


Je ferme.
