### ISSUE TITLE
Drawing: les outils d'edition ne fonctionnent pas

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#426]
### Description

Les boutons d'edition (boutons du bas) du panel du widget de dessin ne fonctionnent pas.

### Comportement attendu

Les boutons fonctionnent.

### Comment reproduire l'anomalie

Essayer d'editer un tracer réaliser avec le widget Drawing.

### Solution possible

![Image](https://github.com/user-attachments/assets/46d6f608-e266-4064-a76f-bddb5ac0078c)
Le "reactive" introduit par [cette PR ](https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/379 )est responsable du bug.

Je ne sais pas ce que son retrait implique pour le reste de l'application.

**Comment by lowzonenose** [comment]
pour info, l'outil de dessin fonctionne sur les branches **feature/connexion** et **feature/connexion2** car elles ne sont pas mergées avec les dernières évolutions
