### ISSUE TITLE
Comportement autour du curseur de la localisation

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/cartes.gouv.fr-entree-carto#434]
### Le besoin que vous rencontrez

Au clic sur ![Image](https://github.com/user-attachments/assets/c35aa54a-1abd-46ba-9e54-0014c96dac7a)
La carte est positionnée à une petite échelle avec le curseur:
![Image](https://github.com/user-attachments/assets/f55140c1-310d-435a-97d7-4d49b183917a)

Quelques remarques : 
- [x] Revoir l'échelle d'affichage. Etre à plus grande échelle me parait plus naturel : 
![Image](https://github.com/user-attachments/assets/6dfb6f73-d284-4da7-a0cf-0020d5a394b7)
- [x] Le clic sur le point donne la position. Le déclenchement du getfeatureinfo est pertubant :
![Image](https://github.com/user-attachments/assets/a5d5e823-f527-4b5b-8064-ceba7f19d2e0)
- [x] le clic sur le point fait apparaitre la longitude et la latitude. Je n'ai pas trouvé de moyen de le fermer.
- [ ] En plus du bouton fermeture sur cette pop-up, je suggère de prévoir une partie des actions qui seront présentes dans le menu contextuel au clic droit (sans être exhaustif et trop affirmatif): 
     - aller vers ce point
     - partir de ce point
     - calculer une isochrone (à challenger, ie on le met et on regarde les stats d'utilisation)

### La solution que vous aimeriez

J'ai un peu écrit les solutions plus haut mais à conforter avec la PO :)

**Comment by elias75015** [comment]
> Le clic sur le point donne la position. Le déclenchement du getfeatureinfo est pertubant

Normalement c'est corrigé par PR côté extensions : https://github.com/IGNF/geopf-extensions-openlayers/pull/301

**Comment by elias75015** [comment]
>  Le clic sur le point donne la position. Le déclenchement du getfeatureinfo est pertubant :

>  Revoir l'échelle d'affichage. Etre à plus grande échelle me parait plus naturel :


Corrigé par PR https://github.com/IGNF/geopf-extensions-openlayers/pull/313

>  En plus du bouton fermeture sur cette pop-up, je suggère de prévoir une partie des actions qui seront présentes dans le menu contextuel au clic droit (sans être exhaustif et trop affirmatif):
> 
>     aller vers ce point
>     partir de ce point
>     calculer une isochrone (à challenger, ie on le met et on regarde les stats d'utilisation)

A voir pour plus tard avec @Kristell-5
