### ISSUE TITLE
Conservation de la carte EP-5

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#59]
EP-5

- [x] La conception en cours de la carte est conservée lorsque l’utilisateur quitte le site. Lorsqu’il rouvrira une nouvelle session, les données qui avaient été ajoutées, le style appliqué et les outils  favoris » seront identiques. Attention s’il n’est pas connecté, c’est configuration peut être perdue si l’utilisateur change de support de consultation ou s’il nettoie son navigateur. 

**Questions** 

RAS : même système que sur le GPP (localStorage) 

![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/10401006/f4f4c937-ab4b-48f3-8413-7109732a031d)

Les clefs préfixées par **"cartes.gouv.fr"** sont les paramètres utilisateurs (disponibles dans le **mapStore**)

Évolutions : 
 * [x] #260
 * [x] #261
 * [x] #262
 * [x] #263
 * [x] #264

A prévoir sur les clefs partagée entre la _carto_ et le site _cartes.gouv.fr_ :
* [ ] #265
* [ ] #266

**Comment by lowzonenose** [comment]
https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/255

Évolutions : 
 * [ ]  construction du permalien
 * [ ]  mettre à jour le flag 'firstVisit'
 * [ ]  structure des couches avec les options
    LAYERID(opacity<number>;(h)idden;(g)ray)<Array>
    ex. ORTHOIMAGERY.ORTHOPHOTOS::GEOPORTAIL:OGC:WMTS(1;h;g)
    avec caractére de séparation des elements de la liste : ','
 * [ ]  structure des contrôles avec les option
    CONTROLID(active<boolean>;disable<boolean>;position<string>)<Array>
    ex. Isocurve(1;0;bottom-left)
    avec caractère de séparation des éléments de la liste : ',' 
 * [ ] zoom absolu ?

A prévoir sur les clefs partagée entre la _carto_ et le site _cartes.gouv.fr_
* [ ] gestion du mode d'affichage (vue-dsfr-scheme / scheme)
* [ ] gestion du consentement (@codegouvfr/react-dsfr finalityConsent eulerianAnalytics)

**Comment by elias75015** [comment]
Une grosse partie de ce ticket est déjà réalisée. Pour le reste, celà dépend des prochaines features : on reporte le reste pour S7

**Comment by elias75015** [comment]
OK pour les deux derniers points :
- consent analytics
- sheme
