### ISSUE TITLE
Vue globale

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#70]
Un bouton pour revenir à une vue globale du territoire qui représente une vue idéale. Le zoom idéal pourrait se baser sur la délimitation géographique de la donnée des métadonnées (délimitation par un rectangle obligatoire). Le logo de la fonctionnalité pourrait prendre la forme soit du territoire souhaité, soit d’un logo unique pouvant reprendre les couleurs du drapeau français.

**Comment by Kristell-5** [comment]
![Image](https://github.com/user-attachments/assets/b0443936-6097-4c02-8e23-1a03ef9dc712)

**Comment by elias75015** [comment]
#314
