### ISSUE TITLE
Accès légende par un bouton dans le sélecteur de couches

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#76]
La première est un accès à la légende par un bouton directement lié à la couche dans le sélecteur de couches.

**Comment by elias75015** [comment]
@Kristell-5 icone dans layerswitcher qui  ouvrirait le widget légende ?

Ou ticket à ignorer ?

**Comment by elias75015** [comment]
Statut à mettre à jour. Je ferme le ticket parent.

**Comment by Kristell-5** [comment]
On ne le fait pas, nous avons un bouton légende.
