### ISSUE TITLE
Accès via un bouton légende classique

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#77]
La seconde est un accès via un bouton légende  classique. La légende dans tous les cas s’ouvrira dans une fenêtre pop-up. La fenêtre pourra être déplacée sur la carte (en cliquant-glissant la fenêtre pop-up) et pourra rester ouverte lors de l’utilisation d’outils par exemple.

**Comment by elias75015** [comment]
Nouveau widget à créer.

Dans un premier temps, les légends sont des images.
A terme, réflexion sur des formats de légende textuels / vectoriels et paramétrage du widget possible.

@Kristell-5 maquette wanted
