### ISSUE TITLE
Widget LayerSwitcher des extensions au DSFR

### ISSUE THREAD

**Issue by elias75015** [IGNF/cartes.gouv.fr-entree-carto#8]
Mise au DSFR du Gestionnaire de couches.

- [x] passer les éléments du layerswitcher actuel ext gpf pour openlayers 8 au DSFR
- [x] définir plus précisément l'attendu UX présenté dans la maquette espace co 
- [x] retravailler le widget en fonction de la maquette 
- [ ] #222
- [x] #232

Lien maquette espace co : https://2fresh-studio.com/projets/ign/2-map.html

**Comment by Kristell-5** [comment]
ok
