### ISSUE TITLE
Gestion de plusieurs fonds de carte différents

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#81]
Gestion de plusieurs fonds de carte différents : 
- Possibilité de conserver plusieurs fonds de plan qui se superposeraient avec des options de paramétrage de visualisation.  
- Possibilité de modifier l’opacité, le passage en noir et blanc de tous les fonds. Si les fonds de cartes ont des options de personnalisation l’utilisateur pourra changer l’apparence globale selon une liste prédéfinie (Exemple : Fond IGN J+1)

**Comment by elias75015** [comment]
reste à faire : #98
