### ISSUE TITLE
Gestion de plusieurs données

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#83]
Une fois les données sélectionnées et ajoutées, elles se superposeraient avec des options de paramétrage de visualisation. (Cf. Gestion des couches une fois ajoutées)

**Comment by Kristell-5** [comment]
Ok

**Comment by Kristell-5** [comment]
Petit bug : lorsqu'on veut ajuster l'opacité en déplaçant le curseur, c'est toute la couche qui se déplace. Du coup, il faut cliquer directement sur l'opacité sans la faire coulisser pour que cela fonctionne.

**Comment by elias75015** [comment]
@Kristell-5 

peux-tu créer une issue dédiée en précisent ton OS et ton navigateur (avec version)?

Je ne constate malheureusement pas sur ma machine.

Merci !

**Comment by Kristell-5** [comment]
Je viens de re-tester pour la rédaction de l'issue et c'est finalement ok !
