### ISSUE TITLE
Lien d’information additionnelle

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#87]
éventuels partenaires à l’élaboration de la donnée, millésime de la donnée et données associées. Les informations s’ouvriront dans un nouvel onglet

**Comment by elias75015** [comment]
Rendu actuel au clic sur le "i" :

![Image](https://github.com/user-attachments/assets/393f1423-afab-4733-a6d2-35269ce6b4d5)


@azarz voir s'il est possible d'améliorer le rendu avec une modale de taille fixe qui se positionne à côté du layerSwitcher.

**Comment by elias75015** [comment]
@azarz Pour l'instant le rendu est toujours le même, n'est-ce pas ?

**Comment by azarz** [comment]
Le rendu est le même, mais le positionnement est meilleur :
![image](https://github.com/user-attachments/assets/8076b3c9-5ad3-4d03-af9e-b8c3da3fef14)
