### ISSUE TITLE
Zoom idéal

### ISSUE THREAD

**Issue by Kristell-5** [IGNF/cartes.gouv.fr-entree-carto#96]
Chaque couche aura une emprise géographique renseignée dans les métadonnées. Le zoom idéal permettra de zoomer ou dézoomer sur l’emprise de la couche de données.

**Comment by elias75015** [comment]
Je ferme pour ce ticket côté entrée carto. Reste à faire côté extensions : https://github.com/IGNF/geoportal-extensions-openlayers/issues/51
